ALTER PROCEDURE dbo.MERGE_INVCBL
AS
BEGIN
MERGE EDW.dbo.INVCBL as target
USING EDW.stg.INVCBL as source
ON
    (
        target.SkuNumber                    = source.SkuNumber
    )
WHEN MATCHED THEN
    UPDATE 
        SET target.OnhandBOY                = source.OnhandBOY,
            target.OnhandBOP                = source.OnhandBOP,
            target.Onhand                   = source.Onhand,
            target.Turns                    = source.Turns,
            target.GMROI                    = source.GMROI,
            target.CurrentWkSls             = source.CurrentWkSls,
            target.WeeklySales01            = source.WeeklySales01,
            target.WeeklySales02            = source.WeeklySales02,
            target.WeeklySales03            = source.WeeklySales03,
            target.WeeklySales04            = source.WeeklySales04,
            target.WeeklySales05            = source.WeeklySales05,
            target.WeeklySales06            = source.WeeklySales06,
            target.WeeklySales07            = source.WeeklySales07,
            target.WeeklySales08            = source.WeeklySales08,
            target.RegSlsUnitsPTD           = source.RegSlsUnitsPTD,
            target.RegSlsUnitsYTD           = source.RegSlsUnitsYTD,
            target.RegSlsAmtPTD             = source.RegSlsAmtPTD,
            target.RegSlsAmtYTD             = source.RegSlsAmtYTD,
            target.RegSlsVATAmtPTD          = source.RegSlsVATAmtPTD,
            target.RegSlsVATAmtYTD          = source.RegSlsVATAmtYTD,
            target.RegCstAmtTD              = source.RegCstAmtTD,
            target.RegCstAmtYTD             = source.RegCstAmtYTD,
            target.AdSlsUnitsPTD            = source.AdSlsUnitsPTD,
            target.AdSlsUnitsYTD            = source.AdSlsUnitsYTD,
            target.AdSlsAmtPTD              = source.AdSlsAmtPTD,
            target.AdSlsAmtYTD              = source.AdSlsAmtYTD,
            target.AdSlsVATAmtPTD           = source.AdSlsVATAmtPTD,
            target.AdSlsVATAmtYTD           = source.AdSlsVATAmtYTD,
            target.AdCstAmtPTD              = source.AdCstAmtPTD,
            target.AdCstAmtYTD              = source.AdCstAmtYTD,
            target.RetSlsUnitsYTD           = source.RetSlsUnitsYTD,
            target.ReceiptUnitsPTD          = source.ReceiptUnitsPTD,
            target.ReceiptUnitsYTD          = source.ReceiptUnitsYTD,
            target.ReceiptAmtPTD            = source.ReceiptAmtPTD,
            target.ReceiptAmtYTD            = source.ReceiptAmtYTD,
            target.TrninUnitsPTD            = source.TrninUnitsPTD,
            target.TrninUnitsYTD            = source.TrninUnitsYTD,
            target.TrnoutUnitsPTD           = source.TrnoutUnitsPTD,
            target.TrnoutUnitsYTD           = source.TrnoutUnitsYTD,
            target.TrnsfrsAmtPTD            = source.TrnsfrsAmtPTD,
            target.TrnsfrsAmtYTD            = source.TrnsfrsAmtYTD,
            target.RTVUnitsPTD              = source.RTVUnitsPTD,
            target.RTVUnitsYTD              = source.RTVUnitsYTD,
            target.RTVAmtPTD                = source.RTVAmtPTD,
            target.RTVAmtYTD                = source.RTVAmtYTD,
            target.AdjUnitsPTD              = source.AdjUnitsPTD,
            target.AdjUnitsYTD              = source.AdjUnitsYTD,
            target.AdjAmtPTD                = source.AdjAmtPTD,
            target.AdjAmtYTD                = source.AdjAmtYTD,
            target.PhyAdjUnitsPTD           = source.PhyAdjUnitsPTD,
            target.PhyAdjUnitsYTD           = source.PhyAdjUnitsYTD,
            target.PhyAdjAmtPTD             = source.PhyAdjAmtPTD,
            target.PhyAdjAmtYTD             = source.PhyAdjAmtYTD,
            target.AverageUnitCost          = source.AverageUnitCost,
            target.AvgInvOH                 = source.AvgInvOH,
            target.AvgInvRtl                = source.AvgInvRtl,
            target.AvgInvCost               = source.AvgInvCost,
            target.Department               = source.Department,
            target.SubDepartment            = source.SubDepartment,
            target.Class                    = source.Class,
            target.SubClass                 = source.SubClass,
            target.VendorNumber             = source.VendorNumber,
            target.StyleNumber              = source.StyleNumber,
            target.POOnOrderQty             = source.POOnOrderQty,
            target.TrfOnOrderQty            = source.TrfOnOrderQty,
            target.InTransitQty             = source.InTransitQty,
            target.MovingAnnualSalesUnit    = source.MovingAnnualSalesUnit,
            target.MovingAnnualSalesRtl     = source.MovingAnnualSalesRtl,
            target.MovingAnnualSalesVAT     = source.MovingAnnualSalesVAT,
            target.MovingAnnualSalesCost    = source.MovingAnnualSalesCost,
            target.LandedAverageCost        = source.LandedAverageCost,
            target.AllocateReserveQuantity  = source.AllocateReserveQuantity,
            target.NonSellableInventoryQty  = source.NonSellableInventoryQty 
WHEN NOT MATCHED BY TARGET
    THEN INSERT
        (
            SkuNumber,
            OnhandBOY,
            OnhandBOP,
            Onhand,
            Turns,
            GMROI,
            CurrentWkSls,
            WeeklySales01,
            WeeklySales02,
            WeeklySales03,
            WeeklySales04,
            WeeklySales05,
            WeeklySales06,
            WeeklySales07,
            WeeklySales08,
            RegSlsUnitsPTD,
            RegSlsUnitsYTD,
            RegSlsAmtPTD,
            RegSlsAmtYTD,
            RegSlsVATAmtPTD,
            RegSlsVATAmtYTD,
            RegCstAmtTD,
            RegCstAmtYTD,
            AdSlsUnitsPTD,
            AdSlsUnitsYTD,
            AdSlsAmtPTD,
            AdSlsAmtYTD,
            AdSlsVATAmtPTD,
            AdSlsVATAmtYTD,
            AdCstAmtPTD,
            AdCstAmtYTD,
            RetSlsUnitsYTD,
            ReceiptUnitsPTD,
            ReceiptUnitsYTD,
            ReceiptAmtPTD,
            ReceiptAmtYTD,
            TrninUnitsPTD,
            TrninUnitsYTD,
            TrnoutUnitsPTD,
            TrnoutUnitsYTD,
            TrnsfrsAmtPTD,
            TrnsfrsAmtYTD,
            RTVUnitsPTD,
            RTVUnitsYTD,
            RTVAmtPTD,
            RTVAmtYTD,
            AdjUnitsPTD,
            AdjUnitsYTD,
            AdjAmtPTD,
            AdjAmtYTD,
            PhyAdjUnitsPTD,
            PhyAdjUnitsYTD,
            PhyAdjAmtPTD,
            PhyAdjAmtYTD,
            AverageUnitCost,
            AvgInvOH,
            AvgInvRtl,
            AvgInvCost,
            Department,
            SubDepartment,
            Class,
            SubClass,
            VendorNumber,
            StyleNumber,
            POOnOrderQty,
            TrfOnOrderQty,
            InTransitQty,
            MovingAnnualSalesUnit,
            MovingAnnualSalesRtl,
            MovingAnnualSalesVAT,
            MovingAnnualSalesCost,
            LandedAverageCost,
            AllocateReserveQuantity,
            NonSellableInventoryQty
        )        
    VALUES
        (
            source.SkuNumber,
            source.OnhandBOY,
            source.OnhandBOP,
            source.Onhand,
            source.Turns,
            source.GMROI,
            source.CurrentWkSls,
            source.WeeklySales01,
            source.WeeklySales02,
            source.WeeklySales03,
            source.WeeklySales04,
            source.WeeklySales05,
            source.WeeklySales06,
            source.WeeklySales07,
            source.WeeklySales08,
            source.RegSlsUnitsPTD,
            source.RegSlsUnitsYTD,
            source.RegSlsAmtPTD,
            source.RegSlsAmtYTD,
            source.RegSlsVATAmtPTD,
            source.RegSlsVATAmtYTD,
            source.RegCstAmtTD,
            source.RegCstAmtYTD,
            source.AdSlsUnitsPTD,
            source.AdSlsUnitsYTD,
            source.AdSlsAmtPTD,
            source.AdSlsAmtYTD,
            source.AdSlsVATAmtPTD,
            source.AdSlsVATAmtYTD,
            source.AdCstAmtPTD,
            source.AdCstAmtYTD,
            source.RetSlsUnitsYTD,
            source.ReceiptUnitsPTD,
            source.ReceiptUnitsYTD,
            source.ReceiptAmtPTD,
            source.ReceiptAmtYTD,
            source.TrninUnitsPTD,
            source.TrninUnitsYTD,
            source.TrnoutUnitsPTD,
            source.TrnoutUnitsYTD,
            source.TrnsfrsAmtPTD,
            source.TrnsfrsAmtYTD,
            source.RTVUnitsPTD,
            source.RTVUnitsYTD,
            source.RTVAmtPTD,
            source.RTVAmtYTD,
            source.AdjUnitsPTD,
            source.AdjUnitsYTD,
            source.AdjAmtPTD,
            source.AdjAmtYTD,
            source.PhyAdjUnitsPTD,
            source.PhyAdjUnitsYTD,
            source.PhyAdjAmtPTD,
            source.PhyAdjAmtYTD,
            source.AverageUnitCost,
            source.AvgInvOH,
            source.AvgInvRtl,
            source.AvgInvCost,
            source.Department,
            source.SubDepartment,
            source.Class,
            source.SubClass,
            source.VendorNumber,
            source.StyleNumber,
            source.POOnOrderQty,
            source.TrfOnOrderQty,
            source.InTransitQty,
            source.MovingAnnualSalesUnit,
            source.MovingAnnualSalesRtl,
            source.MovingAnnualSalesVAT,
            source.MovingAnnualSalesCost,
            source.LandedAverageCost,
            source.AllocateReserveQuantity,
            source.NonSellableInventoryQty
        )
    ;
END;