CREATE PROCEDURE dbo.MERGE_TRFDTL
AS
BEGIN
MERGE   EDW.dbo.TRFDTL as target 
USING   EDW.stg.TRFDTL as source
ON
    (
        target.TransferBatchNumber              = source.TransferBatchNumber
        and target.SkuNumber                    = source.SkuNumber
    )
 WHEN MATCHED THEN UPDATE
        SET target.TransferBatchNumber          = source.TransferBatchNumber,
            target.FromStoreorWarehouse         = source.FromStoreorWarehouse,
            target.ToStoreorWarehouse           = source.ToStoreorWarehouse,
            target.SkuNumber                    = source.SkuNumber,
            target.VendorNumber                 = source.VendorNumber,
            target.Dept                         = source.Dept,
            target.SubDept                      = source.SubDept, 
            target.Class                        = source.Class,
            target.SubClass                     = source.SubClass,
            target.QtyRequest                   = source.QtyRequest,
            target.QtyShipped                   = source.QtyShipped,
            target.QtyReceive                   = source.QtyReceive,
            target.QtyAllocate                  = source.QtyAllocate,
            target.SubstituteNumber             = source.SubstituteNumber,
            target.SubstituteCode               = source.SubstituteCode,
            target.ReceivedWarehouseLocation    = source.ReceivedWarehouseLocation,
            target.UnitCost                     = source.UnitCost,
            target.RetailIn                     = source.RetailIn,
            target.RetailOut                    = source.RetailOut,
            target.[Cube]                       = source.[Cube],
            target.VendorsPartNumber            = source.VendorsPartNumber,
            target.TransferStatusOpt            = source.TransferStatusOpt,
            target.TransferType                 = source.TransferType,
            target.TransferPriorityOpt          = source.TransferPriorityOpt,
            target.WarehouseCycleNumber         = source.WarehouseCycleNumber,
            target.ScheduleWaveNumber           = source.ScheduleWaveNumber,
            target.ScheduleWaveSequence         = source.ScheduleWaveSequence,
            target.ScheduleName                 = source.ScheduleName,
            target.StyleVendor                  = source.StyleVendor,
            target.StyleNumber                  = source.StyleNumber,
            target.ColorCode                    = source.ColorCode,
            target.SizeCode                     = source.SizeCode,
            target.DimensionCode                = source.DimensionCode,
            target.TransferDiscrepancyFlag      = source.TransferDiscrepancyFlag,
            target.CartonShipQty                = source.CartonShipQty,
            target.CartonReceiveQty             = source.CartonReceiveQty,
            target.[Weight]                     = source.[Weight],
            target.CENTURYCODE                  = source.CENTURYCODE,
            target.InitiationDate               = source.InitiationDate,
            target.ShipbyDateCenturyCode        = source.ShipbyDateCenturyCode,
            target.ShipbyDate                   = source.ShipbyDate,
            target.ShippingDateCenturyCode      = source.ShippingDateCenturyCode,
            target.ShippingDate                 = source.ShippingDate,
            target.ReceivingDateCenturyCode     = source.ReceivingDateCenturyCode,
            target.RecvDate                     = source.RecvDate,
            target.Last_Modified                = source.Last_Modified
WHEN NOT MATCHED BY TARGET THEN
        INSERT  
        (
            TransferBatchNumber,
            FromStoreorWarehouse,
            ToStoreorWarehouse,
            SkuNumber,
            VendorNumber,
            Dept,
            SubDept,
            Class,
            SubClass,
            QtyRequest,
            QtyShipped,
            QtyReceive,
            QtyAllocate,
            SubstituteNumber,
            SubstituteCode,
            ReceivedWarehouseLocation,
            UnitCost,
            RetailIn,
            RetailOut,
            [Cube],
            VendorsPartNumber,
            TransferStatusOpt,
            TransferType,
            TransferPriorityOpt,
            WarehouseCycleNumber,
            ScheduleWaveNumber,
            ScheduleWaveSequence,
            ScheduleName,
            StyleVendor,
            StyleNumber,
            ColorCode,
            SizeCode,
            DimensionCode,
            TransferDiscrepancyFlag,
            CartonShipQty,
            CartonReceiveQty,
            [Weight],
            CENTURYCODE,
            InitiationDate,
            ShipbyDateCenturyCode,
            ShipbyDate,
            ShippingDateCenturyCode,
            ShippingDate,
            ReceivingDateCenturyCode,
            RecvDate,
            Last_Modified 
        )
    VALUES
        (
            source.TransferBatchNumber,
            source.FromStoreorWarehouse,
            source.ToStoreorWarehouse,
            source.SkuNumber,
            source.VendorNumber,
            source.Dept,
            source.SubDept,
            source.Class,
            source.SubClass,
            source.QtyRequest,
            source.QtyShipped,
            source.QtyReceive,
            source.QtyAllocate,
            source.SubstituteNumber,
            source.SubstituteCode,
            source.ReceivedWarehouseLocation,
            source.UnitCost,
            source.RetailIn,
            source.RetailOut,
            source.[Cube],
            source.VendorsPartNumber,
            source.TransferStatusOpt,
            source.TransferType,
            source.TransferPriorityOpt,
            source.WarehouseCycleNumber,
            source.ScheduleWaveNumber,
            source.ScheduleWaveSequence,
            source.ScheduleName,
            source.StyleVendor,
            source.StyleNumber,
            source.ColorCode,
            source.SizeCode,
            source.DimensionCode,
            source.TransferDiscrepancyFlag,
            source.CartonShipQty,
            source.CartonReceiveQty,
            source.[Weight],
            source.CENTURYCODE,
            source.InitiationDate,
            source.ShipbyDateCenturyCode,
            source.ShipbyDate,
            source.ShippingDateCenturyCode,
            source.ShippingDate,
            source.ReceivingDateCenturyCode,
            source.RecvDate,
            source.Last_Modified 
        )        
    ;
END;        







