ALTER PROCEDURE dbo.MERGE_POMHDR
AS
BEGIN
MERGE EDW.dbo.POMHDR as target 
USING EDW.stg.POMHDR as source
ON
    (
        target.PONumber                     = source.PONumber
        and target.VendorNumber             = source.VendorNumber
        and target.MasterPONumber           = source.MasterPONumber
        and target.TotalPOCost              = source.TotalPOCost 
    )
WHEN MATCHED 
    THEN UPDATE
        SET 
            target.BackOrderNumber          = source.BackOrderNumber,
            target.VendorNumber             = source.VendorNumber,
            target.TermsCode                = source.TermsCode,
            target.DatingCalcFrom           = source.DatingCalcFrom,
            target.[Status]                 = source.[Status],
            target.Type                     = source.Type,
            target.Destination              = source.Destination,
            target.StoreIfStoreOrder        = source.StoreIfStoreOrder,
            target.ADPO                     = source.ADPO,
            target.DistMethod               = source.DistMethod,
            target.AllowBackorder           = source.AllowBackorder,
            target.Confirmed                = source.Confirmed,
            target.PhoneOrder               = source.PhoneOrder,
            target.BuyerNumber              = source.BuyerNumber,
            target.DepartmentNo             = source.DepartmentNo,
            target.SubDeptNo                = source.SubDeptNo,
            target.OtherVendor              = source.OtherVendor,
            target.FrtPolicyCode            = source.FrtPolicyCode,
            target.FOB                      = source.FOB,
            target.ShipVia1                 = source.ShipVia1,
            target.ShipVia2                 = source.ShipVia2,
            target.ShippingPoint            = source.ShippingPoint,
            target.ShippingComments         = source.ShippingComments,
            target.EntryDateCenturyCode     = source.EntryDateCenturyCode,
            target.EntryDate                = source.EntryDate,
            target.ShipDateCenturyCode      = source.ShipDateCenturyCode,
            target.ShipDate                 = source.ShipDate,
            target.CancelDateCenturyCode    = source.CancelDateCenturyCode,
            target.CancelDate               = source.CancelDate,
            target.ReceiptDateCenturyCode   = source.ReceiptDateCenturyCode,
            target.ReceiptDate              = source.ReceiptDate,
            target.LastChangeDateCenturyCode = source.LastChangeDateCenturyCode,
            target.LastChangeDate           = source.LastChangeDate,
            target.ReviewFreqDays           = source.ReviewFreqDays,
            target.PlanLeadDays             = source.PlanLeadDays,
            target.PointofOrigin            = source.PointofOrigin,
            target.PONote1                  = source.PONote1,
            target.PONote2                  = source.PONote2,
            target.PONote3                  = source.PONote3,
            target.TotalPOCost              = source.TotalPOCost,
            target.TotalPOVat               = source.TotalPOVat,
            target.TotalPORetail            = source.TotalPORetail,
            target.TotalPOCases             = source.TotalPOCases,
            target.TotalPOUnits             = source.TotalPOUnits,
            target.TotalPOWeight            = source.TotalPOWeight,
            target.TarpCharge               = source.TarpCharge,
            target.StopoverCharge           = source.StopoverCharge,
            target.SkidCharge               = source.SkidCharge,
            target.OtherChgAmt              = source.OtherChgAmt,
            target.OtherChgPercent          = source.OtherChgPercent,
            target.BatchCount               = source.BatchCount,
            target.AmountRecRetail          = source.AmountRecRetail,
            target.AmountRecVat             = source.AmountRecVat,
            target.AmountRecCost            = source.AmountRecCost,
            target.TotalPallets             = source.TotalPallets,
            target.TotalCube                = source.TotalCube,
            target.PushDownDateCenturyCode  = source.PushDownDateCenturyCode,
            target.PushDownDate             = source.PushDownDate,
            target.ShipPointNumber          = source.ShipPointNumber,
            target.PayDateDateCenturyCode   = source.PayDateDateCenturyCode,
            target.PayDate                  = source.PayDate,
            target.UMType                   = source.UMType,
            target.TotSkuLevelAlw           = source.TotSkuLevelAlw,
            target.TotVendorLevelAlw        = source.TotVendorLevelAlw,
            target.MasterPONumber           = source.MasterPONumber,
            target.MasterBONumber           = source.MasterBONumber,
            target.POLoadNumber             = source.POLoadNumber,
            target.ConversionRate           = source.ConversionRate,
            target.RateEffectiveCentury     = source.RateEffectiveCentury,
            target.RateEffectiveDate        = source.RateEffectiveDate,
            target.QuickEntryFlag           = source.QuickEntryFlag,
            target.MultLoType               = source.MultLoType,
            target.CreateEDI850             = source.CreateEDI850,
            target.CreateEDI860             = source.CreateEDI860,
            target.ImportDomestic           = source.ImportDomestic,
            target.Publisher                = source.Publisher,
            target.Last_Modified            = source.Last_Modified 
WHEN NOT MATCHED BY TARGET 
        THEN INSERT
        (
            PONumber,
            BackOrderNumber,
            VendorNumber,
            TermsCode,
            DatingCalcFrom,
            [Status],
            [Type],
            Destination,
            StoreIfStoreOrder,
            ADPO,
            DistMethod,
            AllowBackorder,
            Confirmed,
            PhoneOrder,
            BuyerNumber,
            DepartmentNo,
            SubDeptNo,
            OtherVendor,
            FrtPolicyCode,
            FOB,
            ShipVia1,
            ShipVia2,
            ShippingPoint,
            ShippingComments,
            EntryDateCenturyCode,
            EntryDate,
            ShipDateCenturyCode,
            ShipDate,
            CancelDateCenturyCode,
            CancelDate,
            ReceiptDateCenturyCode,
            ReceiptDate,
            LastChangeDateCenturyCode,
            LastChangeDate,
            ReviewFreqDays,
            PlanLeadDays,
            PointofOrigin,
            PONote1,
            PONote2,
            PONote3,
            TotalPOCost,
            TotalPOVat,
            TotalPORetail,
            TotalPOCases,
            TotalPOUnits,
            TotalPOWeight,
            TarpCharge,
            StopoverCharge,
            SkidCharge,
            OtherChgAmt,
            OtherChgPercent,
            BatchCount,
            AmountRecRetail,
            AmountRecVat,
            AmountRecCost,
            TotalPallets,
            TotalCube,
            PushDownDateCenturyCode,
            PushDownDate,
            ShipPointNumber,
            PayDateDateCenturyCode,
            PayDate,
            UMType,
            TotSkuLevelAlw,
            TotVendorLevelAlw,
            MasterPONumber,
            MasterBONumber,
            POLoadNumber,
            ConversionRate,
            RateEffectiveCentury,
            RateEffectiveDate,
            QuickEntryFlag,
            MultLoType,
            CreateEDI850,
            CreateEDI860,
            ImportDomestic,
            Publisher,
            Last_Modified            
        )
    VALUES
        (
            source.PONumber,
            source.BackOrderNumber,
            source.VendorNumber,
            source.TermsCode,
            source.DatingCalcFrom,
            source.Status,
            source.Type,
            source.Destination,
            source.StoreIfStoreOrder,
            source.ADPO,
            source.DistMethod,
            source.AllowBackorder,
            source.Confirmed,
            source.PhoneOrder,
            source.BuyerNumber,
            source.DepartmentNo,
            source.SubDeptNo,
            source.OtherVendor,
            source.FrtPolicyCode,
            source.FOB,
            source.ShipVia1,
            source.ShipVia2,
            source.ShippingPoint,
            source.ShippingComments,
            source.EntryDateCenturyCode,
            source.EntryDate,
            source.ShipDateCenturyCode,
            source.ShipDate,
            source.CancelDateCenturyCode,
            source.CancelDate,
            source.ReceiptDateCenturyCode,
            source.ReceiptDate,
            source.LastChangeDateCenturyCode,
            source.LastChangeDate,
            source.ReviewFreqDays,
            source.PlanLeadDays,
            source.PointofOrigin,
            source.PONote1,
            source.PONote2,
            source.PONote3,
            source.TotalPOCost,
            source.TotalPOVat,
            source.TotalPORetail,
            source.TotalPOCases,
            source.TotalPOUnits,
            source.TotalPOWeight,
            source.TarpCharge,
            source.StopoverCharge,
            source.SkidCharge,
            source.OtherChgAmt,
            source.OtherChgPercent,
            source.BatchCount,
            source.AmountRecRetail,
            source.AmountRecVat,
            source.AmountRecCost,
            source.TotalPallets,
            source.TotalCube,
            source.PushDownDateCenturyCode,
            source.PushDownDate,
            source.ShipPointNumber,
            source.PayDateDateCenturyCode,
            source.PayDate,
            source.UMType,
            source.TotSkuLevelAlw,
            source.TotVendorLevelAlw,
            source.MasterPONumber,
            source.MasterBONumber,
            source.POLoadNumber,
            source.ConversionRate,
            source.RateEffectiveCentury,
            source.RateEffectiveDate,
            source.QuickEntryFlag,
            source.MultLoType,
            source.CreateEDI850,
            source.CreateEDI860,
            source.ImportDomestic,
            source.Publisher,
            source.Last_Modified
        )    
    ;
END;        