USE EDW
GO

CREATE PROCEDURE dbo.MERGE_HSHED
AS
BEGIN
MERGE EDW.dbo.HSHED as target 
USING EDW.stg.HSHED as source
ON
    (
        target.HistorySequenceNumber                    = source.HistorySequenceNumber
    )
 WHEN MATCHED
    THEN UPDATE 
        SET target.HistorySequenceNumber                = source.HistorySequenceNumber,
            target.CustomerNumber                       = source.CustomerNumber,
            target.CompanyNumber                        = source.CompanyNumber,
            target.OrderNumber                          = source.OrderNumber,
            target.OrderGenerationNumber                = source.OrderGenerationNumber,
            target.OrderType                            = source.OrderType,
            target.ShipToNumber                         = source.ShipToNumber,
            target.EntryDate                            = source.EntryDate,
            target.AcknowledgementPrintDate             = source.AcknowledgementPrintDate,
            target.PickSlipPrintDate                    = source.PickSlipPrintDate,
            target.ShipConfirmDate                      = source.ShipConfirmDate,
            target.InvoicePrintDate                     = source.InvoicePrintDate,
            target.QuoteReviewDate                      = source.QuoteReviewDate,
            target.[Route]                              = source.Route,
            target.[Stop]                               = source.Stop,
            target.CompleteShipCode                     = source.CompleteShipCode,
            target.BackorderCode                        = source.BackorderCode,
            target.PrintAcknowledgements                = source.PrintAcknowledgements,
            target.RequestedShipDate                    = source.RequestedShipDate,
            target.InvoiceDate                          = source.InvoiceDate,
            target.DueDate                              = source.DueDate,
            target.NetDate                              = source.NetDate,
            target.FutureDate                           = source.FutureDate,
            target.CustomerPurchaseOrderNumber          = source.CustomerPurchaseOrderNumber,
            target.ShippingInstructions                 = source.ShippingInstructions,
            target.CreditCardAuthorization              = source.CreditCardAuthorization,
            target.CharacterFillerField4                = source.CharacterFillerField4,
            target.MiscellaneousNote                    = source.MiscellaneousNote,
            target.PaymentTypeCode                      = source.PaymentTypeCode,
            target.CreditCardNumber                     = source.CreditCardNumber,
            target.CCExpirationDateMonth                = source.CCExpirationDateMonth,
            target.CCExpirationDateYear                 = source.CCExpirationDateYear,
            target.CashDiscountPercent                  = source.CashDiscountPercent,
            target.CashDiscountAmount                   = source.CashDiscountAmount,
            target.ARTermsCode                          = source.ARTermsCode,
            target.InvoiceNumber                        = source.InvoiceNumber,
            target.OrderReferenceNumber                 = source.OrderReferenceNumber,
            target.ContractNumber                       = source.ContractNumber,
            target.CustomerPriceList                    = source.CustomerPriceList,
            target.PriceDiscountCode                    = source.PriceDiscountCode,
            target.OverridePriceDiscountPercent         = source.OverridePriceDiscountPercent,
            target.TradeDiscountPercent                 = source.TradeDiscountPercent,
            target.WarehouseID                          = source.WarehouseID,
            target.AllocatedCode                        = source.AllocatedCode,
            target.PrimarySalesman                      = source.PrimarySalesman,
            target.SecondSalesman                       = source.SecondSalesman,
            target.ThirdSalesman                        = source.ThirdSalesman,
            target.CommissionPercentRepNumberOne        = source.CommissionPercentRepNumberOne,
            target.CommissionPercentRepNumberTwo        = source.CommissionPercentRepNumberTwo,
            target.CommissionPercentRepNumberThree      = source.CommissionPercentRepNumberThree,
            target.HoldCode                             = source.HoldCode,
            target.LastUsertoReleasethisOrder           = source.LastUsertoReleasethisOrder,
            target.LastHoldCode                         = source.LastHoldCode,
            target.PriorHoldCode                        = source.PriorHoldCode,
            target.OriginalUserId                       = source.OriginalUserId,
            target.LastUserID                           = source.LastUserID,
            target.NumberofItems                        = source.NumberofItems,
            target.NumberofSpecialCharges               = source.NumberofSpecialCharges,
            target.NumberofMessages                     = source.NumberofMessages,
            target.ItemSalesAmount                      = source.ItemSalesAmount,
            target.TotalSpecialCharges                  = source.TotalSpecialCharges,
            target.TradeDiscountAmount                  = source.TradeDiscountAmount,
            target.SalesTaxAmount                       = source.SalesTaxAmount,
            target.FederalExciseAmount                  = source.FederalExciseAmount,
            target.TotalContainerCharge                 = source.TotalContainerCharge,
            target.InvoiceAmount                        = source.InvoiceAmount,
            target.TaxBody                              = source.TaxBody,
            target.SalesTaxPercent                      = source.SalesTaxPercent,
            target.ExemptCode                           = source.ExemptCode,
            target.FederalExciseTaxCode                 = source.FederalExciseTaxCode,
            target.AmountSubjecttoTax                   = source.AmountSubjecttoTax,
            target.ItemExemptAmount1                    = source.ItemExemptAmount1,
            target.ItemExemptAmount2                    = source.ItemExemptAmount2,
            target.ItemExemptAmount3                    = source.ItemExemptAmount3,
            target.DropShipAmount                       = source.DropShipAmount,
            target.DepositAmount                        = source.DepositAmount,
            target.AccountsReceivableCustomerAmount     = source.AccountsReceivableCustomerAmount,
            target.AmountTendered                       = source.AmountTendered,
            target.TotalOrderValue                      = source.TotalOrderValue,
            target.ExtendedOrderCost                    = source.ExtendedOrderCost,
            target.NewOrderCode                         = source.NewOrderCode,
            target.DropShipCode                         = source.DropShipCode,
            target.OrderSource                          = source.OrderSource,
            target.CustomerGLCode                       = source.CustomerGLCode,
            target.ReturntoStock                        = source.ReturntoStock,
            target.Territory                            = source.Territory,
            target.CustomerClass                        = source.CustomerClass,
            target.CustomerSubclass                     = source.CustomerSubclass,
            target.AccountsReceivableCustomerNumber     = source.AccountsReceivableCustomerNumber,
            target.ShippedOrderWeight                   = source.ShippedOrderWeight,
            target.UpdateAR                             = source.UpdateAR,
            target.CustomerSortWord                     = source.CustomerSortWord,
            target.CharacterUserArea15                  = source.CharacterUserArea15,
            target.CharacterFillerField1                = source.CharacterFillerField1,
            target.ParentOrderNumber                    = source.ParentOrderNumber,
            target.TotalCubesShipped                    = source.TotalCubesShipped,
            target.UpdateDemand                         = source.UpdateDemand,
            target.CarrierCode                          = source.CarrierCode,
            target.PrintInvoices                        = source.PrintInvoices,
            target.EDIOrderYorblank                     = source.EDIOrderYorblank,
            target.EDIInvoices                          = source.EDIInvoices,
            target.EDIInvoiceStatus                     = source.EDIInvoiceStatus,
            target.HoldEDIInvoices                      = source.HoldEDIInvoices,
            target.EDIInvoiceInUseWS                    = source.EDIInvoiceInUseWS,
            target.EDIInvoiceCentury                    = source.EDIInvoiceCentury,
            target.EDIInvoiceDateSent                   = source.EDIInvoiceDateSent,
            target.EDIInvoiceTimeSent                   = source.EDIInvoiceTimeSent,
            target.EDIAcknowledgements                  = source.EDIAcknowledgements,
            target.EDIAcknowledgementStatus             = source.EDIAcknowledgementStatus,
            target.HoldEDIAcknwldgmnts                  = source.HoldEDIAcknwldgmnts,
            target.EDIAckInUseWS                        = source.EDIAckInUseWS,
            target.EDIAcknowldgementCentury             = source.EDIAcknowldgementCentury,
            target.EDIAcknowldgementDateSent            = source.EDIAcknowldgementDateSent,
            target.EDIAcknowldgementTimeSent            = source.EDIAcknowldgementTimeSent,
            target.EDIAdvanceShipnotice                 = source.EDIAdvanceShipnotice,
            target.EDIASNStatus                         = source.EDIASNStatus,
            target.HoldEDIASN                           = source.HoldEDIASN,
            target.EDIASNInUseWS                        = source.EDIASNInUseWS,
            target.EDIASNCentury                        = source.EDIASNCentury,
            target.EDIASNDateSent                       = source.EDIASNDateSent,
            target.EDIASNTimeSent                       = source.EDIASNTimeSent,
            target.EDIOrderCreateTime                   = source.EDIOrderCreateTime,
            target.FaxInvoices                          = source.FaxInvoices,
            target.FaxAcknowledgements                  = source.FaxAcknowledgements,
            target.NickName                             = source.NickName,
            target.CancelDateCent                       = source.CancelDateCent,
            target.CancelDate                           = source.CancelDate,
            target.ShiptoGeoCode                        = source.ShiptoGeoCode,
            target.GST                                  = source.GST,
            target.GSTTaxPercent                        = source.GSTTaxPercent,
            target.GSTAmount                            = source.GSTAmount,
            target.PSTYesNoCompounded                   = source.PSTYesNoCompounded,
            target.PSTTaxPercent                        = source.PSTTaxPercent,
            target.PSTAmount                            = source.PSTAmount,
            target.ConsolidatedBillCode                 = source.ConsolidatedBillCode,
            target.ConsolidatedInvControlNumber         = source.ConsolidatedInvControlNumber,
            target.ConsolidatedInvPrtFlag               = source.ConsolidatedInvPrtFlag,
            target.CustomerContractCode                 = source.CustomerContractCode,
            target.Century                              = source.Century,
            target.[AllocationDate]                     = source.[AllocationDate],
            target.ManualReleasedFutureOrder            = source.ManualReleasedFutureOrder,
            target.EntryTime                            = source.EntryTime,
            target.EntryUser                            = source.EntryUser,
            target.AcknowledgePrintTime                 = source.AcknowledgePrintTime,
            target.AcknowledgePrintUser                 = source.AcknowledgePrintUser,
            target.PickSlipPrintTime                    = source.PickSlipPrintTime,
            target.PickSlipPrintUser                    = source.PickSlipPrintUser,
            target.ShipConfirmTime                      = source.ShipConfirmTime,
            target.ShipConfirmUser                      = source.ShipConfirmUser,
            target.InvoicePrintTime                     = source.InvoicePrintTime,
            target.InvoicePrintUser                     = source.InvoicePrintUser,
            target.PackerID                             = source.PackerID,
            target.PickerID                             = source.PickerID,
            target.DriverID                             = source.DriverID,
            target.FOBCode                              = source.FOBCode,
            target.TaxExemptCertificateNumber           = source.TaxExemptCertificateNumber,
            target.ExpirationCentury                    = source.ExpirationCentury,
            target.ExpirationDate                       = source.ExpirationDate,
            target.ProNumber                            = source.ProNumber,
            target.BillOfLadingNumber                   = source.BillOfLadingNumber,
            target.AllItemsBackOrderedFlag              = source.AllItemsBackOrderedFlag,
            target.DaysinProcessCentry                  = source.DaysinProcessCentry,
            target.DaysinProcessDate                    = source.DaysinProcessDate,
            target.DaysinProcessTime                    = source.DaysinProcessTime,
            target.DayendCentry                         = source.DayendCentry,
            target.DayendDate                           = source.DayendDate,
            target.Department                           = source.Department,
            target.InternalVendorNumber                 = source.InternalVendorNumber,
            target.EmailInvoices                        = source.EmailInvoices,
            target.EmailAcknowledgements                = source.EmailAcknowledgements,
            target.Last_Modified                        = source.Last_Modified 
WHEN NOT MATCHED BY TARGET THEN
        INSERT 
            (
                HistorySequenceNumber,
                CustomerNumber,
                CompanyNumber,
                OrderNumber,
                OrderGenerationNumber,
                OrderType,
                ShipToNumber,
                EntryDate,
                AcknowledgementPrintDate,
                PickSlipPrintDate,
                ShipConfirmDate,
                InvoicePrintDate,
                QuoteReviewDate,
                [Route],
                [Stop],
                CompleteShipCode,
                BackorderCode,
                PrintAcknowledgements,
                RequestedShipDate,
                InvoiceDate,
                DueDate,
                NetDate,
                FutureDate,
                CustomerPurchaseOrderNumber,
                ShippingInstructions,
                CreditCardAuthorization,
                CharacterFillerField4,
                MiscellaneousNote,
                PaymentTypeCode,
                CreditCardNumber,
                CCExpirationDateMonth,
                CCExpirationDateYear,
                CashDiscountPercent,
                CashDiscountAmount,
                ARTermsCode,
                InvoiceNumber,
                OrderReferenceNumber,
                ContractNumber,
                CustomerPriceList,
                PriceDiscountCode,
                OverridePriceDiscountPercent,
                TradeDiscountPercent,
                WarehouseID,
                AllocatedCode,
                PrimarySalesman,
                SecondSalesman,
                ThirdSalesman,
                CommissionPercentRepNumberOne,
                CommissionPercentRepNumberTwo,
                CommissionPercentRepNumberThree,
                HoldCode,
                LastUsertoReleasethisOrder,
                LastHoldCode,
                PriorHoldCode,
                OriginalUserId,
                LastUserID,
                NumberofItems,
                NumberofSpecialCharges,
                NumberofMessages,
                ItemSalesAmount,
                TotalSpecialCharges,
                TradeDiscountAmount,
                SalesTaxAmount,
                FederalExciseAmount,
                TotalContainerCharge,
                InvoiceAmount,
                TaxBody,
                SalesTaxPercent,
                ExemptCode,
                FederalExciseTaxCode,
                AmountSubjecttoTax,
                ItemExemptAmount1,
                ItemExemptAmount2,
                ItemExemptAmount3,
                DropShipAmount,
                DepositAmount,
                AccountsReceivableCustomerAmount,
                AmountTendered,
                TotalOrderValue,
                ExtendedOrderCost,
                NewOrderCode,
                DropShipCode,
                OrderSource,
                CustomerGLCode,
                ReturntoStock,
                Territory,
                CustomerClass,
                CustomerSubclass,
                AccountsReceivableCustomerNumber,
                ShippedOrderWeight,
                UpdateAR,
                CustomerSortWord,
                CharacterUserArea15,
                CharacterFillerField1,
                ParentOrderNumber,
                TotalCubesShipped,
                UpdateDemand,
                CarrierCode,
                PrintInvoices,
                EDIOrderYorblank,
                EDIInvoices,
                EDIInvoiceStatus,
                HoldEDIInvoices,
                EDIInvoiceInUseWS,
                EDIInvoiceCentury,
                EDIInvoiceDateSent,
                EDIInvoiceTimeSent,
                EDIAcknowledgements,
                EDIAcknowledgementStatus,
                HoldEDIAcknwldgmnts,
                EDIAckInUseWS,
                EDIAcknowldgementCentury,
                EDIAcknowldgementDateSent,
                EDIAcknowldgementTimeSent,
                EDIAdvanceShipnotice,
                EDIASNStatus,
                HoldEDIASN,
                EDIASNInUseWS,
                EDIASNCentury,
                EDIASNDateSent,
                EDIASNTimeSent,
                EDIOrderCreateTime,
                FaxInvoices,
                FaxAcknowledgements,
                NickName,
                CancelDateCent,
                CancelDate,
                ShiptoGeoCode,
                GST,
                GSTTaxPercent,
                GSTAmount,
                PSTYesNoCompounded,
                PSTTaxPercent,
                PSTAmount,
                ConsolidatedBillCode,
                ConsolidatedInvControlNumber,
                ConsolidatedInvPrtFlag,
                CustomerContractCode,
                Century,
                AllocationDate,
                ManualReleasedFutureOrder,
                EntryTime,
                EntryUser,
                AcknowledgePrintTime,
                AcknowledgePrintUser,
                PickSlipPrintTime,
                PickSlipPrintUser,
                ShipConfirmTime,
                ShipConfirmUser,
                InvoicePrintTime,
                InvoicePrintUser,
                PackerID,
                PickerID,
                DriverID,
                FOBCode,
                TaxExemptCertificateNumber,
                ExpirationCentury,
                ExpirationDate,
                ProNumber,
                BillOfLadingNumber,
                AllItemsBackOrderedFlag,
                DaysinProcessCentry,
                DaysinProcessDate,
                DaysinProcessTime,
                DayendCentry,
                DayendDate,
                Department,
                InternalVendorNumber,
                EmailInvoices,
                EmailAcknowledgements,
                Last_Modified                
            )  
        VALUES
            (
                source.HistorySequenceNumber,
                source.CustomerNumber,
                source.CompanyNumber,
                source.OrderNumber,
                source.OrderGenerationNumber,
                source.OrderType,
                source.ShipToNumber,
                source.EntryDate,
                source.AcknowledgementPrintDate,
                source.PickSlipPrintDate,
                source.ShipConfirmDate,
                source.InvoicePrintDate,
                source.QuoteReviewDate,
                source.[Route],
                source.[Stop],
                source.CompleteShipCode,
                source.BackorderCode,
                source.PrintAcknowledgements,
                source.RequestedShipDate,
                source.InvoiceDate,
                source.DueDate,
                source.NetDate,
                source.FutureDate,
                source.CustomerPurchaseOrderNumber,
                source.ShippingInstructions,
                source.CreditCardAuthorization,
                source.CharacterFillerField4,
                source.MiscellaneousNote,
                source.PaymentTypeCode,
                source.CreditCardNumber,
                source.CCExpirationDateMonth,
                source.CCExpirationDateYear,
                source.CashDiscountPercent,
                source.CashDiscountAmount,
                source.ARTermsCode,
                source.InvoiceNumber,
                source.OrderReferenceNumber,
                source.ContractNumber,
                source.CustomerPriceList,
                source.PriceDiscountCode,
                source.OverridePriceDiscountPercent,
                source.TradeDiscountPercent,
                source.WarehouseID,
                source.AllocatedCode,
                source.PrimarySalesman,
                source.SecondSalesman,
                source.ThirdSalesman,
                source.CommissionPercentRepNumberOne,
                source.CommissionPercentRepNumberTwo,
                source.CommissionPercentRepNumberThree,
                source.HoldCode,
                source.LastUsertoReleasethisOrder,
                source.LastHoldCode,
                source.PriorHoldCode,
                source.OriginalUserId,
                source.LastUserID,
                source.NumberofItems,
                source.NumberofSpecialCharges,
                source.NumberofMessages,
                source.ItemSalesAmount,
                source.TotalSpecialCharges,
                source.TradeDiscountAmount,
                source.SalesTaxAmount,
                source.FederalExciseAmount,
                source.TotalContainerCharge,
                source.InvoiceAmount,
                source.TaxBody,
                source.SalesTaxPercent,
                source.ExemptCode,
                source.FederalExciseTaxCode,
                source.AmountSubjecttoTax,
                source.ItemExemptAmount1,
                source.ItemExemptAmount2,
                source.ItemExemptAmount3,
                source.DropShipAmount,
                source.DepositAmount,
                source.AccountsReceivableCustomerAmount,
                source.AmountTendered,
                source.TotalOrderValue,
                source.ExtendedOrderCost,
                source.NewOrderCode,
                source.DropShipCode,
                source.OrderSource,
                source.CustomerGLCode,
                source.ReturntoStock,
                source.Territory,
                source.CustomerClass,
                source.CustomerSubclass,
                source.AccountsReceivableCustomerNumber,
                source.ShippedOrderWeight,
                source.UpdateAR,
                source.CustomerSortWord,
                source.CharacterUserArea15,
                source.CharacterFillerField1,
                source.ParentOrderNumber,
                source.TotalCubesShipped,
                source.UpdateDemand,
                source.CarrierCode,
                source.PrintInvoices,
                source.EDIOrderYorblank,
                source.EDIInvoices,
                source.EDIInvoiceStatus,
                source.HoldEDIInvoices,
                source.EDIInvoiceInUseWS,
                source.EDIInvoiceCentury,
                source.EDIInvoiceDateSent,
                source.EDIInvoiceTimeSent,
                source.EDIAcknowledgements,
                source.EDIAcknowledgementStatus,
                source.HoldEDIAcknwldgmnts,
                source.EDIAckInUseWS,
                source.EDIAcknowldgementCentury,
                source.EDIAcknowldgementDateSent,
                source.EDIAcknowldgementTimeSent,
                source.EDIAdvanceShipnotice,
                source.EDIASNStatus,
                source.HoldEDIASN,
                source.EDIASNInUseWS,
                source.EDIASNCentury,
                source.EDIASNDateSent,
                source.EDIASNTimeSent,
                source.EDIOrderCreateTime,
                source.FaxInvoices,
                source.FaxAcknowledgements,
                source.NickName,
                source.CancelDateCent,
                source.CancelDate,
                source.ShiptoGeoCode,
                source.GST,
                source.GSTTaxPercent,
                source.GSTAmount,
                source.PSTYesNoCompounded,
                source.PSTTaxPercent,
                source.PSTAmount,
                source.ConsolidatedBillCode,
                source.ConsolidatedInvControlNumber,
                source.ConsolidatedInvPrtFlag,
                source.CustomerContractCode,
                source.Century,
                source.AllocationDate,
                source.ManualReleasedFutureOrder,
                source.EntryTime,
                source.EntryUser,
                source.AcknowledgePrintTime,
                source.AcknowledgePrintUser,
                source.PickSlipPrintTime,
                source.PickSlipPrintUser,
                source.ShipConfirmTime,
                source.ShipConfirmUser,
                source.InvoicePrintTime,
                source.InvoicePrintUser,
                source.PackerID,
                source.PickerID,
                source.DriverID,
                source.FOBCode,
                source.TaxExemptCertificateNumber,
                source.ExpirationCentury,
                source.ExpirationDate,
                source.ProNumber,
                source.BillOfLadingNumber,
                source.AllItemsBackOrderedFlag,
                source.DaysinProcessCentry,
                source.DaysinProcessDate,
                source.DaysinProcessTime,
                source.DayendCentry,
                source.DayendDate,
                source.Department,
                source.InternalVendorNumber,
                source.EmailInvoices,
                source.EmailAcknowledgements,
                source.Last_Modified                 
            ) 
    ;
END;                         