USE EDW
GO

CREATE PROCEDURE dbo.MERGE_RPLPRF
AS
BEGIN
MERGE EDW.dbo.RPLPRF as target
USING EDW.stg.RPLPRF as source
ON
    (
        target.SkuNumber                        = source.SkuNumber
        and target.StoreNumber                  = source.StoreNumber
    )
WHEN MATCHED THEN
    UPDATE 
        SET target.SkuNumber                    = source.SkuNumber,
            target.StoreNumber                  = source.StoreNumber,
            target.ProductStartDateCenturyCode  = source.ProductStartDateCenturyCode,
            target.ProdStartYear                = source.ProdStartYear,
            target.ProdStartMonth               = source.ProdStartMonth,
            target.DateStoreOpenedCenturyCode   = source.DateStoreOpenedCenturyCode,
            target.StoreOpenYear                = source.StoreOpenYear,
            target.StoreOpenMonth               = source.StoreOpenMonth,
            target.[Profile]                    = source.[Profile],
            target.RPLCalc                      = source.RPLCalc,
            target.VendorNumber                 = source.VendorNumber,
            target.ShipPointNum                 = source.ShipPointNum,
            target.ItemStatusCode               = source.ItemStatusCode,
            target.ReplacementSKU               = source.ReplacementSKU,
            target.Options                      = source.Options,
            target.MaxStockOrdTo                = source.MaxStockOrdTo,
            target.DisplayMinOrdTo              = source.DisplayMinOrdTo,
            target.ModelStockCode               = source.ModelStockCode,
            target.StoreWarehouse               = source.StoreWarehouse,
            target.ManFcatDropDateCenturyCode   = source.ManFcatDropDateCenturyCode,
            target.DropManFcatYear              = source.DropManFcatYear,
            target.DropManFcatMonth             = source.DropManFcatMonth,
            target.SameasStoreNumber            = source.SameasStoreNumber,
            target.SameasSkuNumber              = source.SameasSkuNumber,
            target.SafetyStockWks               = source.SafetyStockWks,
            target.BaseSales                    = source.BaseSales,
            target.CalcdTrend                   = source.CalcdTrend,
            target.ActualTrend                  = source.ActualTrend,
            target.CurYrFCastUnits              = source.CurYrFCastUnits,
            target.OrderPercentWeeks            = source.OrderPercentWeeks,
            target.OrderNumberWeeks             = source.OrderNumberWeeks,
            target.VendorLeadTime               = source.VendorLeadTime,
            target.ModelStock                   = source.ModelStock,
            target.MinimumStock                 = source.MinimumStock,
            target.ModelStockRatio              = source.ModelStockRatio,
            target.AdjPerRatio                  = source.AdjPerRatio,
            target.AdjPerRatioPercent           = source.AdjPerRatioPercent,
            target.AdjOrderUpTo                 = source.AdjOrderUpTo,
            target.AdjOrderAt                   = source.AdjOrderAt,
            target.AvgSalesPrevious             = source.AvgSalesPrevious,
            target.AvgSalesNew                  = source.AvgSalesNew,
            target.AvgSalesHistoric             = source.AvgSalesHistoric,
            target.AvgSalesForecast             = source.AvgSalesForecast,
            target.ReviewPeriodDays             = source.ReviewPeriodDays,
            target.StoreAllocMax                = source.StoreAllocMax,
            target.SkuRating1                   = source.SkuRating1,
            target.SkuRankng1                   = source.SkuRankng1,
            target.SkuRating2                   = source.SkuRating2,
            target.SkuRankng2                   = source.SkuRankng2,
            target.SkuRating3                   = source.SkuRating3,
            target.SkuRankng3                   = source.SkuRankng3,
            target.SkuRating4                   = source.SkuRating4,
            target.SkuRankng4                   = source.SkuRankng4,
            target.MaxSafetyStock               = source.MaxSafetyStock,
            target.SafetyStockDays              = source.SafetyStockDays,
            target.SafetyStockUnits             = source.SafetyStockUnits,
            target.TotalRank                    = source.TotalRank,
            target.TotalStores                  = source.TotalStores,
            target.SameasStoreDropDateCenturyCode   = source.SameasStoreDropDateCenturyCode,
            target.SameasStoreDropYear          = source.SameasStoreDropYear,
            target.SameasStoreDropMonth         = source.SameasStoreDropMonth,
            target.SameasStoreForecastUnits     = source.SameasStoreForecastUnits,
            target.Department                   = source.Department,
            target.SubDepartment                = source.SubDepartment,
            target.Class                        = source.Class,
            target.SubClass                     = source.SubClass,
            target.CurWksWghtngFactor           = source.CurWksWghtngFactor,
            target.HistWksWghtngFactor          = source.HistWksWghtngFactor,
            target.PreviousRunsAvgSlsHist       = source.PreviousRunsAvgSlsHist,
            target.DateLastMaint                = source.DateLastMaint,
            target.Last_Modified                = source.Last_Modified 
WHEN NOT MATCHED BY TARGET
        THEN INSERT
        (
            SkuNumber,
            StoreNumber,
            ProductStartDateCenturyCode,
            ProdStartYear,
            ProdStartMonth,
            DateStoreOpenedCenturyCode,
            StoreOpenYear,
            StoreOpenMonth,
            [Profile],
            RPLCalc,
            VendorNumber,
            ShipPointNum,
            ItemStatusCode,
            ReplacementSKU,
            Options,
            MaxStockOrdTo,
            DisplayMinOrdTo,
            ModelStockCode,
            StoreWarehouse,
            ManFcatDropDateCenturyCode,
            DropManFcatYear,
            DropManFcatMonth,
            SameasStoreNumber,
            SameasSkuNumber,
            SafetyStockWks,
            BaseSales,
            CalcdTrend,
            ActualTrend,
            CurYrFCastUnits,
            OrderPercentWeeks,
            OrderNumberWeeks,
            VendorLeadTime,
            ModelStock,
            MinimumStock,
            ModelStockRatio,
            AdjPerRatio,
            AdjPerRatioPercent,
            AdjOrderUpTo,
            AdjOrderAt,
            AvgSalesPrevious,
            AvgSalesNew,
            AvgSalesHistoric,
            AvgSalesForecast,
            ReviewPeriodDays,
            StoreAllocMax,
            SkuRating1,
            SkuRankng1,
            SkuRating2,
            SkuRankng2,
            SkuRating3,
            SkuRankng3,
            SkuRating4,
            SkuRankng4,
            MaxSafetyStock,
            SafetyStockDays,
            SafetyStockUnits,
            TotalRank,
            TotalStores,
            SameasStoreDropDateCenturyCode,
            SameasStoreDropYear,
            SameasStoreDropMonth,
            SameasStoreForecastUnits,
            Department,
            SubDepartment,
            Class,
            SubClass,
            CurWksWghtngFactor,
            HistWksWghtngFactor,
            PreviousRunsAvgSlsHist,
            DateLastMaint,
            Last_Modified             
        )
    VALUES
        (
            source.SkuNumber,
            source.StoreNumber,
            source.ProductStartDateCenturyCode,
            source.ProdStartYear,
            source.ProdStartMonth,
            source.DateStoreOpenedCenturyCode,
            source.StoreOpenYear,
            source.StoreOpenMonth,
            source.[Profile],
            source.RPLCalc,
            source.VendorNumber,
            source.ShipPointNum,
            source.ItemStatusCode,
            source.ReplacementSKU,
            source.Options,
            source.MaxStockOrdTo,
            source.DisplayMinOrdTo,
            source.ModelStockCode,
            source.StoreWarehouse,
            source.ManFcatDropDateCenturyCode,
            source.DropManFcatYear,
            source.DropManFcatMonth,
            source.SameasStoreNumber,
            source.SameasSkuNumber,
            source.SafetyStockWks,
            source.BaseSales,
            source.CalcdTrend,
            source.ActualTrend,
            source.CurYrFCastUnits,
            source.OrderPercentWeeks,
            source.OrderNumberWeeks,
            source.VendorLeadTime,
            source.ModelStock,
            source.MinimumStock,
            source.ModelStockRatio,
            source.AdjPerRatio,
            source.AdjPerRatioPercent,
            source.AdjOrderUpTo,
            source.AdjOrderAt,
            source.AvgSalesPrevious,
            source.AvgSalesNew,
            source.AvgSalesHistoric,
            source.AvgSalesForecast,
            source.ReviewPeriodDays,
            source.StoreAllocMax,
            source.SkuRating1,
            source.SkuRankng1,
            source.SkuRating2,
            source.SkuRankng2,
            source.SkuRating3,
            source.SkuRankng3,
            source.SkuRating4,
            source.SkuRankng4,
            source.MaxSafetyStock,
            source.SafetyStockDays,
            source.SafetyStockUnits,
            source.TotalRank,
            source.TotalStores,
            source.SameasStoreDropDateCenturyCode,
            source.SameasStoreDropYear,
            source.SameasStoreDropMonth,
            source.SameasStoreForecastUnits,
            source.Department,
            source.SubDepartment,
            source.Class,
            source.SubClass,
            source.CurWksWghtngFactor,
            source.HistWksWghtngFactor,
            source.PreviousRunsAvgSlsHist,
            source.DateLastMaint,
            source.Last_Modified              
        )    
    ;
END;        