USE [EDW]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ClusteredIndex-20220502-140706]    Script Date: 5/24/2022 8:51:40 AM ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20220502-140706] ON [dbo].[CSHDEP]
(
	[STORENUMBER] ASC,
	[DEPOSITCENTURY] ASC,
	[DEPOSITDATE] ASC,
	[REGISTERNUMBER] ASC,
	[TILLNUMBER] ASC,
	[REPORTLINENO] ASC,
	[DEPOSITAMOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


