USE [EDW]
GO

/****** Object:  Index [ClusteredIndex-20220505-095836]    Script Date: 5/24/2022 8:54:01 AM ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20220505-095836] ON [dbo].[CSHEGC]
(
	[STORENUMBER] ASC,
	[TRANSACTIONNUMBER] ASC,
	[SEQUENCENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


