USE [EDW]
GO

/****** Object:  Index [IDX_CSHTND_TRANSNUMBER]    Script Date: 5/24/2022 8:56:18 AM ******/
CREATE CLUSTERED INDEX [IDX_CSHTND_TRANSNUMBER] ON [dbo].[CSHTND]
(
	[STORENUMBER] ASC,
	[TRANSACTIONNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


