ALTER PROCEDURE dbo.MERGE_INVMST
AS
BEGIN
MERGE EDW.dbo.INVMST as target
USING EDW.stg.INVMST as source
ON
    (
        target.SkuNumber                    = source.SkuNumber
    )
WHEN MATCHED
    THEN UPDATE
        SET target.SkuNumber                = source.SkuNumber,
            target.CheckDigit               = source.CheckDigit,
            target.ItemDescription          = source.ItemDescription,
            target.StatusCode               = source.StatusCode,
            target.ShortDescription         = source.ShortDescription,
            target.StyleNumber              = source.StyleNumber,
            target.VendorNumber             = source.VendorNumber,
            target.VendorsNumber            = source.VendorsNumber,
            target.ManufNumber              = source.ManufNumber,
            target.ManufsNumber             = source.ManufsNumber,
            target.Department               = source.Department,
            target.SubDepartment            = source.SubDepartment,
            target.Class                    = source.Class,
            target.SubClass                 = source.SubClass,
            target.Buyer                    = source.Buyer,
            target.AdSpace                  = source.AdSpace,
            target.MercuryDistro            = source.MercuryDistro,
            target.BuyCodeCS                = source.BuyCodeCS,
            target.SetCode                  = source.SetCode,
            target.MultVendorInd            = source.MultVendorInd,
            target.PricePrompt              = source.PricePrompt,
            target.ExcldPOSdwnld            = source.ExcldPOSdwnld,
            target.TicketTypeReg            = source.TicketTypeReg,
            target.TicketTypeAd             = source.TicketTypeAd,
            target.NoTicketsItem            = source.NoTicketsItem,
            target.LabelTypeReg             = source.LabelTypeReg,
            target.LabelTypeAd              = source.LabelTypeAd,
            target.MerchGrpNumber           = source.MerchGrpNumber,
            target.ProfileNumber            = source.ProfileNumber,
            target.ModuleNumber             = source.ModuleNumber,
            target.SkuType                  = source.SkuType,
            target.ColorCode                = source.ColorCode,
            target.Size                     = source.Size,
            target.HazardousCode            = source.HazardousCode,
            target.Merchandiser             = source.Merchandiser,
            target.SubstituteSKU            = source.SubstituteSKU,
            target.CoreSKU                  = source.CoreSKU,
            target.ReplacementSKU           = source.ReplacementSKU,
            target.SellingUM                = source.SellingUM,
            target.SellBuyConFct            = source.SellBuyConFct,
            target.BuyUM                    = source.BuyUM,
            target.InnerPack                = source.InnerPack,
            target.CasePack                 = source.CasePack,
            target.HoldOrder                = source.HoldOrder,
            target.MinOrderQty              = source.MinOrderQty,
            target.Orderat                  = source.Orderat,
            target.MaximumAnytime           = source.MaximumAnytime,
            target.ModelStock               = source.ModelStock,
            target.MinDisplayQty            = source.MinDisplayQty,
            target.StockinMult              = source.StockinMult,
            target.ReplenishmentCode        = source.ReplenishmentCode,
            target.ManufList                = source.ManufList,
            target.HomeCost                 = source.HomeCost,
            target.LastVendorCost           = source.LastVendorCost,
            target.LastCostDate             = source.LastCostDate,
            target.LastCostCentury          = source.LastCostCentury,
            target.NextVendorCost           = source.NextVendorCost,
            target.NextCostDate             = source.NextCostDate,
            target.NextCostCentury          = source.NextCostCentury,
            target.Weight                   = source.Weight,
            target.Cube                     = source.Cube,
            target.Length                   = source.Length,
            target.Width                    = source.Width,
            target.Height                   = source.Height,
            target.DateLastMaint            = source.DateLastMaint,
            target.CenturyLastMaint         = source.CenturyLastMaint,
            target.VndrPalletTiQty          = source.VndrPalletTiQty,
            target.VndrPalletHiQty          = source.VndrPalletHiQty,
            target.ShipPointNumber          = source.ShipPointNumber,
            target.DistributionMethod       = source.DistributionMethod,
            target.HoldWholesaleOrder       = source.HoldWholesaleOrder,
            target.InventoryGroup           = source.InventoryGroup,
            target.Dimension                = source.Dimension,
            target.fieldnotused             = source.fieldnotused,
            target.VendorCost               = source.VendorCost,
            target.FiveSignedNumericZeroDec = source.FiveSignedNumericZeroDec,
            target.VelocityRankCode1        = source.VelocityRankCode1,
            target.VelocityRankCode2        = source.VelocityRankCode2,
            target.VelocityRankCode3        = source.VelocityRankCode3,
            target.VelocityRankCode4        = source.VelocityRankCode4,
            target.ReplenStartCent          = source.ReplenStartCent,
            target.ReplenStartDate          = source.ReplenStartDate,
            target.SeasonCode               = source.SeasonCode,
            target.CenturyDeadDate          = source.CenturyDeadDate,
            target.DeadDate                 = source.DeadDate,
            target.InitialRetail            = source.InitialRetail,
            target.InitialHomeCost          = source.InitialHomeCost,
            target.HandlingCode             = source.HandlingCode,
            target.Attribute1               = source.Attribute1,
            target.Attribute2               = source.Attribute2,
            target.Attribute3               = source.Attribute3,
            target.Attribute4               = source.Attribute4,
            target.Attribute5               = source.Attribute5,
            target.ChainPrice               = source.ChainPrice,
            target.ZonePrice                = source.ZonePrice,
            target.StorePrice               = source.StorePrice,
            target.StyleVendor              = source.StyleVendor,
            target.CoordinateGroupNumber    = source.CoordinateGroupNumber,
            target.SKULeadTime              = source.SKULeadTime
WHEN NOT MATCHED BY TARGET
    THEN INSERT
        (
            SkuNumber,
            CheckDigit,
            ItemDescription,
            StatusCode,
            ShortDescription,
            StyleNumber,
            VendorNumber,
            VendorsNumber,
            ManufNumber,
            ManufsNumber,
            Department,
            SubDepartment,
            Class,
            SubClass,
            Buyer,
            AdSpace,
            MercuryDistro,
            BuyCodeCS,
            SetCode,
            MultVendorInd,
            PricePrompt,
            ExcldPOSdwnld,
            TicketTypeReg,
            TicketTypeAd,
            NoTicketsItem,
            LabelTypeReg,
            LabelTypeAd,
            MerchGrpNumber,
            ProfileNumber,
            ModuleNumber,
            SkuType,
            ColorCode,
            Size,
            HazardousCode,
            Merchandiser,
            SubstituteSKU,
            CoreSKU,
            ReplacementSKU,
            SellingUM,
            SellBuyConFct,
            BuyUM,
            InnerPack,
            CasePack,
            HoldOrder,
            MinOrderQty,
            Orderat,
            MaximumAnytime,
            ModelStock,
            MinDisplayQty,
            StockinMult,
            ReplenishmentCode,
            ManufList,
            HomeCost,
            LastVendorCost,
            LastCostDate,
            LastCostCentury,
            NextVendorCost,
            NextCostDate,
            NextCostCentury,
            [Weight],
            [Cube],
            [Length],
            Width,
            Height,
            DateLastMaint,
            CenturyLastMaint,
            VndrPalletTiQty,
            VndrPalletHiQty,
            ShipPointNumber,
            DistributionMethod,
            HoldWholesaleOrder,
            InventoryGroup,
            Dimension,
            fieldnotused,
            VendorCost,
            FiveSignedNumericZeroDec,
            VelocityRankCode1,
            VelocityRankCode2,
            VelocityRankCode3,
            VelocityRankCode4,
            ReplenStartCent,
            ReplenStartDate,
            SeasonCode,
            CenturyDeadDate,
            DeadDate,
            InitialRetail,
            InitialHomeCost,
            HandlingCode,
            Attribute1,
            Attribute2,
            Attribute3,
            Attribute4,
            Attribute5,
            ChainPrice,
            ZonePrice,
            StorePrice,
            StyleVendor,
            CoordinateGroupNumber,
            SKULeadTime
        )             
    VALUES
        (
            source.SkuNumber,
            source.CheckDigit,
            source.ItemDescription,
            source.StatusCode,
            source.ShortDescription,
            source.StyleNumber,
            source.VendorNumber,
            source.VendorsNumber,
            source.ManufNumber,
            source.ManufsNumber,
            source.Department,
            source.SubDepartment,
            source.Class,
            source.SubClass,
            source.Buyer,
            source.AdSpace,
            source.MercuryDistro,
            source.BuyCodeCS,
            source.SetCode,
            source.MultVendorInd,
            source.PricePrompt,
            source.ExcldPOSdwnld,
            source.TicketTypeReg,
            source.TicketTypeAd,
            source.NoTicketsItem,
            source.LabelTypeReg,
            source.LabelTypeAd,
            source.MerchGrpNumber,
            source.ProfileNumber,
            source.ModuleNumber,
            source.SkuType,
            source.ColorCode,
            source.Size,
            source.HazardousCode,
            source.Merchandiser,
            source.SubstituteSKU,
            source.CoreSKU,
            source.ReplacementSKU,
            source.SellingUM,
            source.SellBuyConFct,
            source.BuyUM,
            source.InnerPack,
            source.CasePack,
            source.HoldOrder,
            source.MinOrderQty,
            source.Orderat,
            source.MaximumAnytime,
            source.ModelStock,
            source.MinDisplayQty,
            source.StockinMult,
            source.ReplenishmentCode,
            source.ManufList,
            source.HomeCost,
            source.LastVendorCost,
            source.LastCostDate,
            source.LastCostCentury,
            source.NextVendorCost,
            source.NextCostDate,
            source.NextCostCentury,
            source.Weight,
            source.Cube,
            source.Length,
            source.Width,
            source.Height,
            source.DateLastMaint,
            source.CenturyLastMaint,
            source.VndrPalletTiQty,
            source.VndrPalletHiQty,
            source.ShipPointNumber,
            source.DistributionMethod,
            source.HoldWholesaleOrder,
            source.InventoryGroup,
            source.Dimension,
            source.fieldnotused,
            source.VendorCost,
            source.FiveSignedNumericZeroDec,
            source.VelocityRankCode1,
            source.VelocityRankCode2,
            source.VelocityRankCode3,
            source.VelocityRankCode4,
            source.ReplenStartCent,
            source.ReplenStartDate,
            source.SeasonCode,
            source.CenturyDeadDate,
            source.DeadDate,
            source.InitialRetail,
            source.InitialHomeCost,
            source.HandlingCode,
            source.Attribute1,
            source.Attribute2,
            source.Attribute3,
            source.Attribute4,
            source.Attribute5,
            source.ChainPrice,
            source.ZonePrice,
            source.StorePrice,
            source.StyleVendor,
            source.CoordinateGroupNumber,
            source.SKULeadTime
        )  
    ;      
END;    