DECLARE @Start DATETIME = CAST(GETDATE() - 1 as date)
DECLARE @End DATETIME = CAST(GETDATE() - 1095 as date)
SET @End = DATEADD(SECOND, 86399, @End)


SELECT * FROM EDW.STG.PIE022(NOLOCK)
WHERE @Start > @End