(CALENDARDATE == "0") || (CALENDARDATE == "101") ? NULL(DT_DBTIMESTAMP) : (DT_DBTIMESTAMP)(SUBSTRING(CALENDARDATE,1,2) + "-" + SUBSTRING(CALENDARDATE,3,2) + "-" + SUBSTRING(CALENDARDATE,5,2))

(DATELASTMAINT == "0") || (DATELASTMAINT == "101") ? NULL(DT_DBTIMESTAMP) : (DT_DBTIMESTAMP)(SUBSTRING(DATELASTMAINT,1,4) + "-" + SUBSTRING(DATELASTMAINT,5,2) + "-" + SUBSTRING(DATELASTMAINT,7,2))

(DATEOPENED == "0") || (DATEOPENED == "101") ? NULL(DT_DBTIMESTAMP) : (DT_DBTIMESTAMP)(SUBSTRING(DATEOPENED,1,2) + "-" + SUBSTRING(DATEOPENED,3,2) + "-" + SUBSTRING(DATEOPENED,5,2))

(INVOICEDATE == "0") || (INVOICEDATE == "101") ? NULL(DT_DBTIMESTAMP) : (DT_DBTIMESTAMP)(SUBSTRING(INVOICEDATE,1,4) + "-" + SUBSTRING(INVOICEDATE,5,2) + "-" + SUBSTRING(INVOICEDATE,7,2))