INSERT INTO EDW.dbo.PIESCH
	  ( 
	   [StoreNumber]
      ,[Countdate]
      ,[TypeCode]
      ,[CountID]
      ,[Polled]
      ,[Posted]
      ,[ErrorFlag]
      ,[ChangedbyUserId]
      ,[ChangedDate]
      ,[SummaryFlag]
      ,[FinalReportSent]
      ,[Last_Modified]
	  )
SELECT [StoreNumber]
      ,[Countdate]
      ,[TypeCode]
      ,[CountID]
      ,[Polled]
      ,[Posted]
      ,[ErrorFlag]
      ,[ChangedbyUserId]
      ,[ChangedDate]
      ,[SummaryFlag]
      ,[FinalReportSent]
      ,[Last_Modified]
  FROM [EDW].[stg].[PIESCH]