SELECT OBCONO AS CompanyNumber,
       OBCSNO AS CustomerNumber,
       OBORNO AS OrderNumber,
       OBORGN AS OrderGenerationNumber,
       OBHSSQ AS HistorySequenceNumber,
       OBORSQ AS OrderSequenceNumber,
       OBLITP AS LineItemType,
       OBSHP# AS ShipToNumber,
       OBSLNO AS PrimarySalesmanNumber,
       OBWHID AS WarehouseID,
       OBORTP AS OrderType,
       OBPRLS AS PriceList,
       OBOHLD AS OrderHoldCode,
       OBRQCC AS Century1,
       CASE OBRQCC
           WHEN 19 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OBRQDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 20 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OBRQDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS RequestDate,
       OBLTCD AS LotCode,
       OBITNO AS ItemNumber,
       OBITD1 AS ItemDescription1,
       OBITD2 AS ItemDescription2,
       OBQTOR AS QuantityOrdered,
       OBQTSH AS QuantityShipped,
       OBBOQT AS QuantityBackordered,
       OBUNMS AS UnitofMeasure,
       OBUMCD AS UMCode,
       OBITCL AS ItemClass,
       OBITSC AS ItemSubclass,
       OBNOST AS NonStockCode,
       OBLSPR AS ListPrice,
       OBDSCP AS ItemDiscountPercent,
       OBFPOC AS FinalPriceOverrideCode,
       OBQDST AS QtyDscType, --(I=Item,C=Class,blank=none)
       OBFL01 AS CharacterFillerField1,
       OBADSP AS AdditionalDiscountPercent,
       OBASLP AS ActualSellPrice,
       OBLNAM AS TotalLineAmount,
       OBLTCH AS LotChargeCode,
       OBSYAM AS SystemTotalLineAmount,
       OBPRUM AS Pricing,
       OBTXCD AS TaxableCode,
       OBEXMT AS TaxExemptCode,
       OBCNCH AS ContainerCharge,
       OBFETX AS FederalExciseTaxAmount,
       OBACDC AS AllowCashDiscountCode,
       OBWHLC AS WarehouseLocation,
       OBCAVC AS CurrentAverageCost,
       OBOUPR AS OurPurchaseOrderNumber,
       OBALCD AS AllocatedCode,
       OBLNVL AS LineValue,
       OBCOVC AS CostOverrideCode,
       OBCSTX AS InvoiceCost,
       OBUNWT AS UnitWeight,
       OBEXWT AS ExtendedWeight,
       OBDRSH AS DropShipCode,
       OBREUS AS ReUsableCode,
       OBBLQT AS KitBuildQuantity,
       OBACNO AS GeneralLedgerAccountNumber,
       OBQBCL AS QuantityBreakClass,
       OBDSMR AS DiscountMarkupCode1,
       OBENSQ AS OrderEntrySequence,
       OBIVCC AS Century2,
       CASE OBIVCC
           WHEN 19 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OBIVDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 20 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OBIVDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS InvoiceDate,
       OBPRCL AS PriceClass,
       OBCNCD AS ContractCode,
       OBCSRT AS CustomerSortWord,
       OBIQDS AS ItemQuantityDiscount,
       OBUS10 AS UserArea,
       OBBMCD AS BillofMaterialsCode,
       OBITDP AS ItemDescPrintCode,
       OBITGL AS ItemGLCode,
       OBSOSQ AS SpecialOrderSequence,
       OBIIPG AS InsertInProgressFlag,
       OBASCM AS AssignedComplete,
       OBWMCD AS WHMgmtCode,
       OBFL02 AS CharacterFillerField2,
       OBPROR AS ParentOrderNumber,
       OBETSQ AS EntrySequenceNumber,
       OBOGQT AS OriginalQuantity,
       OBORIT AS OriginalItemNumber,
       OBRRCD AS ReplacementReasonCode,
       OBORWH AS OriginalWarehouse,
       OBRTRC AS ReturnReasonCode,
       OBIPSQ AS InvoicePrintSequence,
       OBRSCD AS ProcuctRestrictionCode,
       OBCMCS AS CommissionCost,
       OBRBID AS RebateId,
       OBINCS AS InventoryCost,
       OBRBVN AS RebateVendorNumber,
       OBRBPN AS RebatePending,
       OBCOUM AS CustomerOrder,
       OBDOCN AS DocumentNumber,
       OBELR# AS EDILineReferenceNumber,
       OBCQTO AS CustomerOrderQuantity,
       OBCPUM AS CustomerPricing,
       OBOPAR AS OriginalParOrderNumber,
       OBOESQ AS OriginalEntrySeqNmbr,
       OBLTXA AS LineItemTaxAmount,
       OBOTXA AS OrderTaxAmount,
       OBCBCD AS ConsolidatedBillCode,
       OBCICT AS ConsolidatedInvControlNumber,
       OBCIPF AS ConsolidatedInvPrtFlag,
       OBITCT AS ItemContractCode,
       OBINVP AS InventoryPostedFlag,
       OBRTVL AS ReturntoVendorLogNumber,
       OBDIPT AS DaysinProcessType
    FROM APLUS2FAW.HSDET
    WHERE OBIVDT = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)
    OR OBIVDT = 0