SELECT OAHSSQ AS HistorySequenceNumber,
       OACSNO AS CustomerNumber,
       OACONO AS CompanyNumber,
       OAORNO AS OrderNumber,
       OAORGN AS OrderGenerationNumber,
       OAORTP AS OrderType,
       OASHP# AS ShipToNumber,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAENTD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS EntryDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAACDP, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS AcknowledgementPrintDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAPSPD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS PickSlipPrintDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OASC9D, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS ShipConfirmDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAINVD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS InvoicePrintDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAQRVD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS QuoteReviewDate,
       OAROUT AS Route,
       OASTOP AS Stop,
       OACSCD AS CompleteShipCode,
       OABKCD AS BackorderCode,
       OAPRAC AS PrintAcknowledgements,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OARQSD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS RequestedShipDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAIPDT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS InvoiceDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OADEDT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS DueDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OANETD, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS NetDate,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAFTDT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS FutureDate,
       OACSPO AS CustomerPurchaseOrderNumber,
       OASPIN AS ShippingInstructions,
       OACCAU AS CreditCardAuthorization,
       OAFL04 AS CharacterFillerField4,
       OANOTE AS MiscellaneousNote,
       OAPYTP AS PaymentTypeCode,
       OACRCD AS CreditCardNumber,
       SUBSTR(CHAR(LPAD(OAEXPD, 4, 0)), 1, 2) AS CCExpirationDateMonth,
       SUBSTR(CHAR(LPAD(OAEXPD, 4, 0)), 3, 4) AS CCExpirationDateYear,
       OACDSP AS CashDiscountPercent,
       OACDAM AS CashDiscountAmount,
       OATMCD AS ARTermsCode,
       OAINNO AS InvoiceNumber,
       OAORRF AS OrderReferenceNumber,
       OACNNR AS ContractNumber,
       OACPRL AS CustomerPriceList,
       OACPRC AS PriceDiscountCode,
       OAOVDP AS OverridePriceDiscountPercent,
       OATDPC AS TradeDiscountPercent,
       OAWHID AS WarehouseID,
       OAALCD AS AllocatedCode,
       OASLS1 AS PrimarySalesman,
       OASLS2 AS SecondSalesman,
       OASLS3 AS ThirdSalesman,
       OACPR1 AS CommissionPercentRepNumberOne,
       OACPR2 AS CommissionPercentRepNumberTwo,
       OACPR3 AS CommissionPercentRepNumberThree,
       OAHLCD AS HoldCode,
       OALUSR AS LastUsertoReleasethisOrder,
       OALSHL AS LastHoldCode,
       OAPRHL AS PriorHoldCode,
       OAORU8 AS OriginalUserId,
       OALUS8 AS LastUserID,
       OANOIT AS NumberofItems,
       OANOSC AS NumberofSpecialCharges,
       OANOMS AS NumberofMessages,
       OAISAM AS ItemSalesAmount,
       OASCAM AS TotalSpecialCharges,
       OATDAM AS TradeDiscountAmount,
       OATXAM AS SalesTaxAmount,
       OAFEAM AS FederalExciseAmount,
       OACNCT AS TotalContainerCharge,
       OAINAM AS InvoiceAmount,
       OATXBD AS TaxBody,
       OATXPC AS SalesTaxPercent,
       OAEXCD AS ExemptCode,
       OAEXCS AS FederalExciseTaxCode,
       OAASTX AS AmountSubjecttoTax,
       OAEXM1 AS ItemExemptAmount1,
       OAEXM2 AS ItemExemptAmount2,
       OAEXM3 AS ItemExemptAmount3,
       OADSAM AS DropShipAmount,
       OADPAM AS DepositAmount,
       OAARC$ AS AccountsReceivableCustomerAmount,
       OATNAM AS AmountTendered,
       OAORVL AS TotalOrderValue,
       OAORCS AS ExtendedOrderCost,
       OANWOR AS NewOrderCode,
       OADRSH AS DropShipCode,
       OAORSC AS OrderSource,
       OACSGL AS CustomerGLCode,
       OARTST AS ReturntoStock,
       OATERT AS Territory,
       OACSCL AS CustomerClass,
       OACSSC AS CustomerSubclass,
       OAARCN AS AccountsReceivableCustomerNumber,
       OASHWT AS ShippedOrderWeight,
       OAUPAR AS UpdateAR,
       OACSRT AS CustomerSortWord,
       OAUS15 AS CharacterUserArea15,
       OAFL01 AS CharacterFillerField1,
       OAPROR AS ParentOrderNumber,
       OATCBS AS TotalCubesShipped,
       OAUPDM AS UpdateDemand,
       OACACD AS CarrierCode,
       OAPRTI AS PrintInvoices,
       OAEIOR AS EDIOrderYorblank,
       OAEIIN AS EDIInvoices,
       OAEINS AS EDIInvoiceStatus,
       OAEIIH AS HoldEDIInvoices,
       OAEIIW AS EDIInvoiceInUseWS,
       OAEINC AS EDIInvoiceCentury,
       CASE OAEINC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OAEIND + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAEIND, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS EDIInvoiceDateSent,
       TIME(to_date(DIGITS(CAST(OAEINT AS DEC(6, 0))), 'HH24MISS')) AS EDIInvoiceTimeSent,
       OAEIAK AS EDIAcknowledgements,
       OAEAKS AS EDIAcknowledgementStatus,
       OAEIAH AS HoldEDIAcknwldgmnts,
       OAEIAW AS EDIAckInUseWS,
       OAEAKC AS EDIAcknowldgementCentury,
       CASE OAEAKC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OAEAKD + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAEAKD, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS EDIAcknowldgementDateSent,
       TIME(to_date(DIGITS(CAST(OAEAKT AS DEC(6, 0))), 'HH24MISS')) AS EDIAcknowldgementTimeSent,
       OAEIAS AS EDIAdvanceShipnotice,
       OAEASS AS EDIASNStatus,
       OAEASH AS HoldEDIASN,
       OAEISW AS EDIASNInUseWS,
       OAEASC AS EDIASNCentury,
       CASE OAEASC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OAEASD + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAEASD, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS EDIASNDateSent,
       TIME(to_date(DIGITS(CAST(OAEAST AS DEC(6, 0))), 'HH24MISS')) AS EDIASNTimeSent,
       TIME(to_date(DIGITS(CAST(OAEICT AS DEC(6, 0))), 'HH24MISS')) AS EDIOrderCreateTime,
       OAFXIN AS FaxInvoices,
       OAFXAK AS FaxAcknowledgements,
       OANKNM AS NickName,
       OACLCC AS CancelDateCent,
       CASE OACLCC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OACLDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OACLDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS CancelDate,
       OASGEO AS ShiptoGeoCode,
       OAGTYN AS GST,
       OAGTXP AS GSTTaxPercent,
       OAGTXA AS GSTAmount,
       OAPTYN AS PSTYesNoCompounded,
       OAPTXP AS PSTTaxPercent,
       OAPTXA AS PSTAmount,
       OACBCD AS ConsolidatedBillCode,
       OACICT AS ConsolidatedInvControlNumber,
       OACIPF AS ConsolidatedInvPrtFlag,
       OACSCT AS CustomerContractCode,
       OAALCC AS Century,
--case OAALCC
--when 0 then varchar_format(timestamp_format(char(OAALDT+19000000), 'YYYMMDD'), 'YYYYMMDD')
--when 1 then varchar_format(timestamp_format(char(LPAD(OAALDT,6,0)),'YYMMDD'),'YYMMDD') end as AllocationDate,
       OAMRLF AS ManualReleasedFutureOrder,
       TIME(to_date(DIGITS(CAST(OAETTM AS DEC(6, 0))), 'HH24MISS')) AS EntryTime,
       OAETUS AS EntryUser,
       TIME(to_date(DIGITS(CAST(OAACTM AS DEC(6, 0))), 'HH24MISS')) AS AcknowledgePrintTime,
       OAACUS AS AcknowledgePrintUser,
       TIME(to_date(DIGITS(CAST(OAPPTM AS DEC(6, 0))), 'HH24MISS')) AS PickSlipPrintTime,
       OAPPUS AS PickSlipPrintUser,
       TIME(to_date(DIGITS(CAST(OASCTM AS DEC(6, 0))), 'HH24MISS')) AS ShipConfirmTime,
       OASCUS AS ShipConfirmUser,
       TIME(to_date(DIGITS(CAST(OAINTM AS DEC(6, 0))), 'HH24MISS')) AS InvoicePrintTime,
       OAINUR AS InvoicePrintUser,
       OAPACC AS PackerID,
       OAPICC AS PickerID,
       OADRVC AS DriverID,
       OAFOBC AS FOBCode,
       OAEXNO AS TaxExemptCertificateNumber,
       OAEXCC AS ExpirationCentury,
       CASE OAEXCC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OAEXDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OAEXDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS ExpirationDate,
       OAPRON AS ProNumber,
       OABOLN AS BillOfLadingNumber,
       OAOBOF AS AllItemsBackOrderedFlag,
       OADPCC AS DaysinProcessCentry,
       CASE OADPCC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OADPDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OADPDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DaysinProcessDate,
       TIME(to_date(DIGITS(CAST(OADPTM AS DEC(6, 0))), 'HH24MISS')) AS DaysinProcessTime,
       OADNCC AS DayendCentry,
       CASE OADNCC
           WHEN 19 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(OADNDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 20 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(OADNDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DayendDate,
       OADEPT AS Department,
       OAIAVN AS InternalVendorNumber,
       OAEMIN AS EmailInvoices,
       OAEMAK AS EmailAcknowledgements
    FROM APLUS2FAW.HSHED
--    WHERE OAENTD > (SELECT VARCHAR_FORMAT(CHAR(LAST_DAY(CURRENT DATE) + 1 DAY - 3 YEARS), 'YYYYMMDD') AS FIRST_DAY FROM SYSIBM.SYSDUMMY1)