SELECT a.INUMBR AS SkuNumber,
       IATR AS Attribute,
       IVAL AS Value,
       CASE IMCENT
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IMDATE + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IMDATE, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateLastMaint
    FROM MM4R4LIB.INVATR a
         INNER JOIN MM4R4LIB.INVMST b
             ON a.INUMBR = b.INUMBR
   WHERE IMDATE = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)         