SELECT a.INUMBR AS SkuNumber,
       IATR AS Attribute,
       IVAL AS Value,
       CASE IMCENT
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IMDATE + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IMDATE, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateLastMaint
    FROM MM4R4LIB.INVATR a
         INNER JOIN MM4R4LIB.INVMST b
             ON a.INUMBR = b.INUMBR
   WHERE IMDATE > (SELECT VARCHAR_FORMAT(CHAR(LAST_DAY(CURRENT DATE) + 1 day - 3 years),'YYMMDD') AS FIRST_DAY FROM SYSIBM.SYSDUMMY1)
   OR IMDATE = 0
   