SELECT a.INUMBR AS SkuNumber,
       CBHBOY AS OnhandBOY,
       CBHBOP AS OnhandBOP,
       CBHAND AS Onhand,
       CBTRNS AS Turns,
       CBGMRI AS GMROI,
       CBWKCR AS CurrentWkSls,
       CBWK01 AS WeeklySales01,
       CBWK02 AS WeeklySales02,
       CBWK03 AS WeeklySales03,
       CBWK04 AS WeeklySales04,
       CBWK05 AS WeeklySales05,
       CBWK06 AS WeeklySales06,
       CBWK07 AS WeeklySales07,
       CBWK08 AS WeeklySales08,
       CBRSUP AS RegSlsUnitsPTD,
       CBRSUY AS RegSlsUnitsYTD,
       CBRSDP AS RegSlsAmtPTD,
       CBRSDY AS RegSlsAmtYTD,
       CBVRSP AS RegSlsVATAmtPTD,
       CBVRSY AS RegSlsVATAmtYTD,
       CBRCSP AS RegCstAmtTD,
       CBRCSY AS RegCstAmtYTD,
       CBASUP AS AdSlsUnitsPTD,
       CBASUY AS AdSlsUnitsYTD,
       CBASDP AS AdSlsAmtPTD,
       CBASDY AS AdSlsAmtYTD,
       CBVASP AS AdSlsVATAmtPTD,
       CBVASY AS AdSlsVATAmtYTD,
       CBACSP AS AdCstAmtPTD,
       CBACSY AS AdCstAmtYTD,
       CBRETS AS RetSlsUnitsYTD,
       CBRCUP AS ReceiptUnitsPTD,
       CBRCUY AS ReceiptUnitsYTD,
       CBRCDP AS ReceiptAmtPTD,
       CBRCDY AS ReceiptAmtYTD,
       CBTIUP AS TrninUnitsPTD,
       CBTIUY AS TrninUnitsYTD,
       CBTOUP AS TrnoutUnitsPTD,
       CBTOUY AS TrnoutUnitsYTD,
       CBTFDP AS TrnsfrsAmtPTD,
       CBTFDY AS TrnsfrsAmtYTD,
       CBRVUP AS RTVUnitsPTD,
       CBRVUY AS RTVUnitsYTD,
       CBRVDP AS RTVAmtPTD,
       CBRVDY AS RTVAmtYTD,
       CBAJUP AS AdjUnitsPTD,
       CBAJUY AS AdjUnitsYTD,
       CBAJDP AS AdjAmtPTD,
       CBAJDY AS AdjAmtYTD,
       CBPHUP AS PhyAdjUnitsPTD,
       CBPHUY AS PhyAdjUnitsYTD,
       CBPHDP AS PhyAdjAmtPTD,
       CBPHDY AS PhyAdjAmtYTD,
       CBAVGC AS AverageUnitCost,
       CBAVOH AS AvgInvOH,
       CBAVRT AS AvgInvRtl,
       CBAVCS AS AvgInvCost,
       CBDEPT AS Department,
       CBSDPT AS SubDepartment,
       CBCLAS AS Class,
       CBSCLS AS SubClass,
       CBVNDR AS VendorNumber,
       CBSTYL AS StyleNumber,
       CBPOOQ AS POOnOrderQty,
       CBTOOQ AS TrfOnOrderQty,
       CBINTQ AS InTransitQty,
       CBMASU AS MovingAnnualSalesUnit,
       CBMASD AS MovingAnnualSalesRtl,
       CBMASV AS MovingAnnualSalesVAT,
       CBMASC AS MovingAnnualSalesCost,
       CBLAVC AS LandedAverageCost,
       CBARQT AS AllocateReserveQuantity,
       CBNSQT AS NonSellableInventoryQty,
       IMCENT AS DLM_Century,
       case IMCENT 
        when 0 then varchar_format(timestamp_format(char(IMDATE+19000000), 'YYYYMMDD'), 'YYYYMMDD')
        when 1 then varchar_format(timestamp_format(char(LPAD(IMDATE,6,0)),'YYMMDD'),'YYMMDD') end as DateLastMaint
    FROM MM4R4LIB.INVCBL a
         INNER JOIN MM4R4LIB.INVMST b
             ON a.INUMBR = b.INUMBR
WHERE IMDATE = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)
OR CHAR(b.IMCENT) = 0             