SELECT INUMBR AS SkuNumber,
       ICHECK AS CheckDigit,
       IDESCR AS ItemDescription,
       IDSCCD AS StatusCode,
       ISORT AS ShortDescription,
       ISTYL# AS StyleNumber,
       ASNUM AS VendorNumber,
       IVNDP# AS VendorsNumber,
       IMFGR AS ManufNumber,
       IMFGNO AS ManufsNumber,
       IDEPT AS Department,
       ISDEPT AS SubDepartment,
       ICLAS AS Class,
       ISCLAS AS SubClass,
       BYRNUM AS Buyer,
       IASPAC AS AdSpace,
       IADVYN AS MercuryDistro,
       IBUYCD AS BuyCodeCS,
       ISET AS SetCode,
       IWARNT AS MultVendorInd,
       IPRMPT AS PricePrompt,
       IPRVNT AS ExcldPOSdwnld,
       ITKTTR AS TicketTypeReg,
       ITKTTA AS TicketTypeAd,
       ITKT# AS NoTicketsItem,
       ILBLTR AS LabelTypeReg,
       ILBLTA AS LabelTypeAd,
       IFINLN AS MerchGrpNumber,
       IPROFL AS ProfileNumber,
       IMODUL AS ModuleNumber,
       ISTYPE AS SkuType,
       ISCOLR AS ColorCode,
       ISSIZE AS Size,
       IHAZCD AS HazardousCode,
       MCHNUM AS Merchandiser,
       ISUBST AS SubstituteSKU,
       ICORE AS CoreSKU,
       IREPL AS ReplacementSKU,
       ISLUM AS SellingUM,
       IUMCV2 AS SellBuyConFct,
       IBYUM AS BuyUM,
       IMINPK AS InnerPack,
       ISTDPK AS CasePack,
       IHLDOR AS HoldOrder,
       IMOQTY AS MinOrderQty,
       IMNSTK AS Orderat,
       IMXSTK AS MaximumAnytime,
       IMDSTK AS ModelStock,
       IDSPLY AS MinDisplayQty,
       IOMULT AS StockinMult,
       IRPLCD AS ReplenishmentCode,
       IMFPRC AS ManufList,
       ICUCST AS HomeCost,
       ILSCST AS LastVendorCost,
       CASE ILSCCN
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(ILSCDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(ILSCDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS LastCostDate,
       ILSCCN AS LastCostCentury,
       INXCST AS NextVendorCost,
       CASE INXCCN
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(INXCDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(INXCDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS NextCostDate,
       INXCCN AS NextCostCentury,
       IWGHT AS Weight,
       ICUBE AS Cube,
       IDLGTH AS Length,
       IDWDTH AS Width,
       IDHGHT AS Height,
       CASE IMCENT
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IMDATE + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IMDATE, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateLastMaint,
       IMCENT AS CenturyLastMaint,
       IVPLTI AS VndrPalletTiQty,
       IVPLHI AS VndrPalletHiQty,
       SHPNUM AS ShipPointNumber,
       IDISTM AS DistributionMethod,
       IHLDWO AS HoldWholesaleOrder,
       IIGNUM AS InventoryGroup,
       ISDIM AS Dimension,
       IVATCD AS fieldnotused,
       IFCCST AS VendorCost,
       IPLAN AS FiveSignedNumericZeroDec,
       IVLRK1 AS VelocityRankCode1,
       IVLRK2 AS VelocityRankCode2,
       IVLRK3 AS VelocityRankCode3,
       IVLRK4 AS VelocityRankCode4,
       IRPLCN AS ReplenStartCent,
       CASE IRPLCN
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IRPLDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IRPLDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS ReplenStartDate,
       ISEASN AS SeasonCode,
       IDEADC AS CenturyDeadDate,
       CASE IDEADC
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IDEADD + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IDEADD, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DeadDate,
       INLRTL AS InitialRetail,
       INLCST AS InitialHomeCost,
       IHANDL AS HandlingCode,
       IATRB1 AS Attribute1,
       IATRB2 AS Attribute2,
       IATRB3 AS Attribute3,
       IATRB4 AS Attribute4,
       IATRB5 AS Attribute5,
       IPRCCH AS ChainPrice,
       IPRCZN AS ZonePrice,
       IPRCST AS StorePrice,
       IASNUM AS StyleVendor,
       ICORGP AS CoordinateGroupNumber,
       ILEAD AS SKULeadTime
    FROM MM4R4LIB.INVMST
--    WHERE IMDATE = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)