SELECT COUNT(*)
    FROM MM4R4LIB.PIE022 a
    INNER JOIN MM4R4LIB.INVMST b
        ON a.CBSKU = b.INUMBR
    WHERE CBPDAT > (SELECT VARCHAR_FORMAT(CHAR(LAST_DAY(CURRENT DATE) + 1 day - 3 years),'YYYYMMDD') AS FIRST_DAY FROM SYSIBM.SYSDUMMY1)
    
--19,636,246    
