SELECT CBCID AS COUNTIDNUMBER,
       CBSTR AS STORENUMBER,
       CBSKU AS SKUNUMBER,
       CBQCNT AS QTYCOUNTED,
       CBDEPT AS JDADEPARTMENT,
       CBSDPT AS JDASUBDEPARTMENT,
       CBCLAS AS JDACLASS,
       CBSCLS AS JDASUBCLASS,
       CBBDPT AS BAMDEPARTMENT,
       CBBCTG AS BAMCATEGORY,
       to_date(CHAR(CBXDAT), 'YYYYMMDD') AS DATECOUNTED,
       CBSQTY AS STOCKTOQTY,
       CBOQTY AS ONHANDQTY,
       CBRQTY AS ROLLBACKONHANDQTY,
       CBAQTY AS ADJUSTMENTQTY,
       to_date(CHAR(CBPDAT), 'YYYYMMDD') AS DATEPOSTED,
       TIME(to_date(DIGITS(CAST(CBPTIM AS DEC(6, 0))), 'HH24MISS')) AS TIMEPOSTED,
       CBPBY AS POSTEDBY,
       CBCPRC AS CURRENTPRICE,
       CBTYPE AS SKUTYPE,
       CBSTAT AS SKUSTATUS,
        CASE IMCENT
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(IMDATE + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(IMDATE, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateLastMaint
    FROM MM4R4LIB.PIE022 a
    INNER JOIN MM4R4LIB.INVMST b
        ON a.CBSKU = b.INUMBR
    WHERE IMDATE >= (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)
--    ORDER BY CBPDAT DESC