SELECT RSSTR AS STORENUMBER,
       RSSKU AS SKUNUMBER,
       RSISBN AS PRIMARYISBN,
       RSDWIN AS DWITEMNUMBER,
       RSQTY1 AS STOCKTOQTY,
       RSQTY2 AS ONHANDQTY,
       RSSTAT AS SKUSTATUSCODE,
       RSTYPE AS SKUTYPECODE,
       RSRPCD AS SKUREPLENCODE,
       to_date(CHAR(RSCDAT), 'YYYYMMDD') AS DATECREATED,
       RSDEPT AS DEPT,
       RSSDPT AS SUBDEPT,
       RSCLAS AS CLASS,
       RSSCLS AS SUBCLASS,
       case IMCENT 
        when 0 then varchar_format(timestamp_format(char(IMDATE+19000000), 'YYYYMMDD'), 'YYYYMMDD')
        when 1 then varchar_format(timestamp_format(char(LPAD(IMDATE,6,0)),'YYMMDD'),'YYMMDD') end as DateLastMaint
    FROM MM4R4LIB.RDI010 a
    INNER JOIN MM4R4LIB.INVMST b
        ON a.RSSKU = b.INUMBR
    WHERE IMDATE = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)