SELECT COUNT(*)
    FROM MM4R4LIB.RDI010 a
    INNER JOIN MM4R4LIB.INVMST b
        ON a.RSSKU = b.INUMBR
    WHERE IMDATE > (SELECT VARCHAR_FORMAT(CHAR(LAST_DAY(CURRENT DATE) + 1 day - 3 years),'YYMMDD') AS FIRST_DAY FROM SYSIBM.SYSDUMMY1)
    
--21,397,101    