SELECT a.INUMBR AS SkuNumber,
       ISTORE AS StoreNumber,
       RFSTCN AS ProductStartDateCenturyCode,
       SUBSTR(CHAR(LPAD(RFSTDT, 4, 0)), 1, 2) AS ProdStartYear,
       SUBSTR(CHAR(LPAD(RFSTDT, 4, 0)), 3, 4) AS ProdStartMonth,
       RFOPCN AS DateStoreOpenedCenturyCode,
       SUBSTR(CHAR(LPAD(RFOPDT, 4, 0)), 1, 2) AS StoreOpenYear,
       SUBSTR(CHAR(LPAD(RFOPDT, 4, 0)), 3, 4) AS StoreOpenMonth,
       RFPROF AS Profile,
       RFRPCD AS RPLCalc,
       RFANUM AS VendorNumber,
       RFSNUM AS ShipPointNum,
       RFDSCD AS ItemStatusCode,
       RFREPL AS ReplacementSKU,
       RFDIST AS Options,
       RFMSTK AS MaxStockOrdTo,
       RFDSPY AS DisplayMinOrdTo,
       RFMCOD AS ModelStockCode,
       RFWHSE AS StoreWarehouse,
       RFFDCN AS ManFcatDropDateCenturyCode,
       SUBSTR(CHAR(LPAD(RFFDDT, 4, 0)), 1, 2) AS DropManFcatYear,
       SUBSTR(CHAR(LPAD(RFFDDT, 4, 0)), 3, 4) AS DropManFcatMonth,
       RFSSTR AS SameasStoreNumber,
       RFSSKU AS SameasSkuNumber,
       RFVWKS AS SafetyStockWks,
       RFBSLS AS BaseSales,
       RFTRND AS CalcdTrend,
       RFATRN AS ActualTrend,
       RFFCUN AS CurYrFCastUnits,
       RFLPWS AS OrderPercentWeeks,
       RFL#WS AS OrderNumberWeeks,
       RFLEAD AS VendorLeadTime,
       RFMAXS AS ModelStock,
       RFMINS AS MinimumStock,
       RFMRAT AS ModelStockRatio,
       RFPRAT AS AdjPerRatio,
       RFPPCT AS AdjPerRatioPercent,
       RFMAX AS AdjOrderUpTo,
       RFMIN AS AdjOrderAt,
       RFASWP AS AvgSalesPrevious,
       RFASWN AS AvgSalesNew,
       RFASWH AS AvgSalesHistoric,
       RFASWF AS AvgSalesForecast,
       RFRVPR AS ReviewPeriodDays,
       RFSAM AS StoreAllocMax,
       RFRAT1 AS SkuRating1,
       RFRNK1 AS SkuRankng1,
       RFRAT2 AS SkuRating2,
       RFRNK2 AS SkuRankng2,
       RFRAT3 AS SkuRating3,
       RFRNK3 AS SkuRankng3,
       RFRAT4 AS SkuRating4,
       RFRNK4 AS SkuRankng4,
       RFMXSS AS MaxSafetyStock,
       RFSSDY AS SafetyStockDays,
       RFSSUN AS SafetyStockUnits,
       RFRATT AS TotalRank,
       RFSTRT AS TotalStores,
       RFSDCN AS SameasStoreDropDateCenturyCode,
       SUBSTR(CHAR(LPAD(RFFDDT, 4, 0)), 1, 2) AS SameasStoreDropYear,
       SUBSTR(CHAR(LPAD(RFFDDT, 4, 0)), 3, 4) AS SameasStoreDropMonth,
       RFSCUN AS SameasStoreForecastUnits,
       RFDEPT AS Department,
       RFSDPT AS SubDepartment,
       RFCLAS AS Class,
       RFSCLS AS SubClass,
       RFWFC1 AS CurWksWghtngFactor,
       RFWFC2 AS HistWksWghtngFactor,
       RFPSWH AS PreviousRunsAvgSlsHist,
       case IMCENT 
        when 0 then varchar_format(timestamp_format(char(IMDATE+19000000), 'YYYYMMDD'), 'YYYYMMDD')
        when 1 then varchar_format(timestamp_format(char(LPAD(IMDATE,6,0)),'YYMMDD'),'YYMMDD') end as DateLastMaint
    FROM MM4R4LIB.RPLPRF a
         INNER JOIN MM4R4LIB.INVMST b
             ON a.INUMBR = b.INUMBR
    WHERE IMDATE = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)          