SELECT DEBNBR AS DebitNumber,
       STRNBR AS StoreNumber,
       VNDNBR AS VendorNumber,
       SCANID AS ScanCode,
       SKUNBR AS SkuNumber,
       DEPTKY AS Dept,
       ONHDKY AS MMSOnHand,
       STATKY AS SKUStatus,
       TYPEKY AS SkuType,
       STRQTY AS StoreQtyReturned,
       RTNQTY AS QuantityReturned,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(RTNDATE, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS DateReturned,
       TIME(to_date(DIGITS(CAST(RTNTIME AS DEC(6, 0))), 'HH24MISS')) AS TimeReturned,
       STATUS AS StatusFlag,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(CRTDAT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS CreateDate,
       CRTUSR AS CreateUser,
       CRTPGM AS CreateProgram,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(CHGDAT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS ChangeDate,
       CHGUSR AS ChangeUser,
       CHGPGM AS ChangeProgram,
       STATMNT AS StatementField,
       varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(RCDAT, 8, 0)), 'YYYYMMDD'), 'YYYYMMDD') AS ReconciledDate,
       LRCVQTY AS LastRecvQty
    FROM MM4R4LIB.RTVTRN
    WHERE CRTDAT = (SELECT VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYMMDD') - 1 FROM SYSIBM.SYSDUMMY1)    