SELECT STRNUM AS StoreNumber,
       STRNAM AS StoreName,
       STADD1 AS AddressLine1,
       STADD2 AS AddressLine2,
       STADD3 AS AddressLine3,
       STCITY AS City,
       STPVST AS ProvinceStateCode,
       STCNTY AS County,
       STCTRY AS Country,
       STZIP AS Zip,
       STPHON AS StorePhoneNo,
       STFAXN AS StoreFaxNo,
       STSHRT AS ShortName,
       REGNUM AS RegionNumber,
       STMNGR AS ManagersName,
       STSCEN AS CenturyCodeOpened,
       CASE STSCEN
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(STSDAT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(STSDAT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateOpened,
       STRETL AS RetailSqFtMtr,
       STPOLL AS OnInterface,
       STSNDY AS OpenSunday,
       STRHDO AS StoreOffice,
       STBACT AS StoreBankAccount1,
       STRWHS AS WarehouseNumber,
       STRDST AS DistrictNumber,
       STRCMP AS NCNewORComp,
       STRTYP AS StoreType,
       STOUTQ AS PrintQueue,
       STCOMP AS GLCompanyNo,
       STCNTR AS CountryCode,
       STGLYN AS ActiveonGL,
       STAPYN AS ActiveonAP,
       STARYN AS ActiveonAR,
       STLCN# AS LastMerchCountNumber,
       ZONNUM AS ZoneNumber,
       STAVGC AS CostingMethod,
       STSCLK AS SalesAuditClerk,
       STMSTK AS ModelStoreCode,
       STAYES AS AllowAPAllocation,
       STAFCT AS APAllocationFactor,
       RPLZN AS ReplenishmentZne,
       STPRMS AS PromoMdlStKCde,
       STRPON AS ReplenishmentOn,
       STCLCN AS CenturyCodeClosed,
       CASE STCLCN
           WHEN 0 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(STCLDT + 19000000), 'YYYYMMDD'), 'YYYYMMDD')
           WHEN 1 THEN varchar_format(TIMESTAMP_FORMAT(CHAR(LPAD(STCLDT, 6, 0)), 'YYMMDD'), 'YYMMDD')
       END AS DateClosed,
       STFACT AS FinancialAccount,
       STBANK AS StoreBankAccount2,
       SAN# AS SanNumber
    FROM MM4R4LIB.TBLSTR